import { useMemo, useState, type CSSProperties } from 'react'
import { ArrowDown, ArrowDownRight, ArrowRight, ArrowUpRight, Asterisk, Blocks, Braces, Check, ChevronRight, Code2, Database, FileText, GitBranch, Layers, Search, SlidersHorizontal, Sparkles, Terminal, Users, Workflow, X } from 'lucide-react'
import { Link, Navigate, NavLink, useParams } from 'react-router-dom'
import { ApproachSection, FunctionLegend, Page, PrimitiveCard, PrimitiveDiagram, PrimitiveLink, PrimitiveName, ProblemList, PseudoCode, SEO, WaitlistForm } from '../components/ui'
import { primitiveAliases, primitiveById, primitives, problemBySlug, problems, type PrimitiveId } from '../content/data'

const buildingBlocks: { name: string; id?: PrimitiveId; icon: typeof Braces; question: string; description: string; code: string; use: string }[] = [
  { name: 'if / else', icon: GitBranch, question: 'Do I already have a reliable signal?', description: 'The customer selected “billing” in a form? Route it with ordinary code. No model required.', code: 'if (ticket.selectedTopic === "billing") {\n  route(ticket, "billing");\n}', use: 'Structured signals' },
  { name: 'classify()', id: 'classify', icon: SlidersHorizontal, question: 'Which team should handle this?', description: 'A fuzzy switch statement: map “I was charged twice” to billing. Use confidence to decide when to fall back.', code: 'const intent = await classify(ticket.text, [\n  "billing", "technical", "account", "other"\n]);\n\nif (intent.label !== "other" && intent.confidence >= 0.8) {\n  route(ticket, intent.label);\n} else {\n  queueForReview(ticket);\n}', use: 'Known categories' },
  { name: 'askSmart()', id: 'askSmart', icon: Sparkles, question: 'What about the ambiguous messages?', description: '“My upgrade failed, but I was still charged.” Spend more reasoning here—not on every ticket. A person checks the suggested route.', code: 'const suggestion = await askSmart(\n  "Choose a support queue. Explain your reasoning.",\n  { context: ticket.text, schema: routingSchema }\n);\n\nqueueForReview({ ticket, suggestion });', use: 'The tricky cases' },
  { name: 'askCheap()', id: 'askCheap', icon: FileText, question: 'Can a small model handle the writing?', description: 'Once the right team is known, draft a short acknowledgment from approved facts. A narrow text task does not need your biggest model.', code: 'const draft = await askCheap(\n  "Write a short acknowledgment. Do not promise a resolution.",\n  { context: { issue: ticket.text, team: assignedTeam } }\n);\n\nshowDraftToAgent(draft);', use: 'Simple text tasks' },
  { name: 'Review queue', icon: Users, question: 'Who owns the decision when we’re unsure?', description: 'A review queue is regular application code. Keep a person in the loop for unfamiliar or high-stakes messages.', code: 'if (isHighStakes(ticket) || !hasReliableRoute(ticket)) {\n  queueForReview(ticket);\n}', use: 'Human judgment' },
]

function blockStyle(id?: PrimitiveId): CSSProperties {
  const primitive = id ? primitiveById(id) : undefined
  return { '--primitive-color': primitive?.color ?? '#5f6951', '--primitive-tint': primitive?.tint ?? '#eef0e7' } as CSSProperties
}

export function HomePage() {
  return <Page><SEO title="Same engineer. Bigger toolbox." description="Learn how to apply AI to real engineering problems. Read small TypeScript pseudo-programs, compare the building blocks, and understand what to build—and what not to."/><div className="landing">
    <section className="landing-hero landing-shell">
      <div className="hero-kicker"><span className="live-dot"/> FOR ENGINEERS WHO ALREADY BUILD</div>
      <div className="landing-hero-heading"><h1>Same engineer.<br/><span>Bigger toolbox.</span><Asterisk className="heading-asterisk" aria-hidden="true" strokeWidth={2.6}/></h1><div className="hero-aside"><p>You know how to build software.<br/>Now learn where AI fits.</p><span className="hand-note">Not more theory.<br/>Better engineering instincts.</span><ArrowDownRight className="aside-arrow" size={36} strokeWidth={1.2}/></div></div>
      <div className="landing-hero-bottom"><p>APIs. Databases. Queues. <strong>And now, AI functions.</strong><br/>Learn to use the right building blocks for real problems.</p><div className="landing-actions"><Link className="landing-button" to="/problems">Pick a real problem <ArrowRight size={17}/></Link><a className="landing-secondary" href="#toolbox">Explore the toolbox <ArrowDown size={15}/></a></div></div>
      <ProblemWorkbench/>
      <div className="hero-footnote"><span><Code2 size={14}/> LESS “HOW DO TRANSFORMERS WORK?”</span><span>MORE “WHAT SHOULD I BUILD?” <ArrowDownRight size={14}/></span></div>
    </section>
    <section className="toolbox-section" id="toolbox"><div className="landing-shell"><div className="section-topline"><span className="mono-label">01 / THE MENTAL MODEL</span><span className="mono-label muted">NEW FUNCTIONS. SAME ENGINEERING.</span></div><div className="toolbox-heading"><h2>AI isn’t the whole system.<br/>It’s <span>part of the stack.</span></h2><p>Think in functions, not model names.<br/>Classify a message. Extract some fields.<br/>Find a match. Keep the rest in code.</p></div><div className="toolbox-tray"><div className="tray-group familiar"><span className="tray-label">THE ONES YOU KNOW</span><div className="tray-blocks"><ToolTile icon={Braces} name="APIs"/><ToolTile icon={Database} name="Databases"/><ToolTile icon={Workflow} name="Queues"/><ToolTile icon={GitBranch} name="Business logic"/></div></div><span className="tray-plus" aria-hidden="true">+</span><div className="tray-group new"><span className="tray-label"><span className="live-dot"/> YOUR AI FUNCTION TOOLBOX</span><div className="tray-blocks"><ToolTile icon={SlidersHorizontal} id="classify"/><ToolTile icon={FileText} id="extract"/><ToolTile icon={Layers} id="embed"/><ToolTile icon={Sparkles} id="askSmart"/></div></div></div><div className="toolbox-caption"><span><Blocks size={15}/> A teaching vocabulary, not a package to install.</span><Link to="/primitives">Explore all {primitives.length} functions <ArrowRight size={15}/></Link></div></div></section>
    <section className="problem-section landing-shell" id="real-problems"><div className="section-topline"><span className="mono-label">02 / START WITH A REAL PROBLEM</span><span className="mono-label muted">NO HELLO-WORLD CHATBOTS</span></div><div className="problem-section-heading"><h2>Think in problems.<br/>Not in prompts.</h2><Link className="landing-secondary" to="/problems">Explore all {problems.length} problems <ArrowRight size={16}/></Link></div><div className="landing-problem-grid"><LandingProblem slug="route-support-tickets" number="01" category="OPERATIONS" icon={GitBranch} title="Send each ticket to the right team." functions={['classify', 'askSmart']} question="Does every ticket need a big model?"/><LandingProblem slug="natural-language-code-search" number="02" category="DEVELOPER TOOLS" icon={Search} title="Find code by what it does." functions={['embed', 'search', 'rerank']} question="Keywords, meaning—or both?"/><LandingProblem slug="extract-messy-invoices" number="03" category="DOCUMENTS" icon={FileText} title="Turn messy invoices into clean data." functions={['extract', 'inspect']} question="What can you trust a model to extract?"/></div><div className="problem-section-note"><span>One problem. Multiple small programs.</span> The interesting part is knowing which one to choose.</div></section>
    <section className="method-section"><div className="landing-shell"><div className="section-topline"><span className="mono-label">03 / BUILD YOUR ENGINEERING INTUITION</span><Terminal size={18}/></div><div className="method-grid"><div className="method-intro"><h2>Not a course.<br/>A new way to<br/><span>look at a problem.</span></h2><p>Read an approach like you read code.<br/>See where AI enters the program.<br/>Understand why it belongs there.</p><Link className="landing-secondary" to="/problems">See a problem breakdown <ArrowRight size={16}/></Link></div><div className="method-steps"><MethodStep number="01" title="Start with the messy reality." text="Real inputs. Real constraints. A problem worth solving." detail="problem → constraints"/><MethodStep number="02" title="Read the different ways to build it." text="Small TypeScript pseudo-programs. Colored AI calls. Ordinary code around them." detail="functions → control flow → trade-offs"/><MethodStep number="03" title="Take the judgment with you." text="Know what to use, what to measure, and what not to build." detail="intuition → your next project"/></div></div></div></section>
    <section className="landing-cta landing-shell"><div className="cta-mark" aria-hidden="true"><Braces/><span>+</span><Sparkles/></div><span className="mono-label">YOU DON’T NEED TO BECOME AN AI RESEARCHER.</span><h2>Just an engineer who<br/>knows <span>when to use AI.</span></h2><div className="landing-actions"><Link className="landing-button" to="/problems">Start with a problem <ArrowRight size={17}/></Link><Link className="landing-secondary" to="/waitlist">Get early access <ArrowUpRight size={16}/></Link></div><p>Build the intuition. Keep building software.</p></section>
  </div></Page>
}

function ProblemWorkbench() {
  const [selected, setSelected] = useState(1)
  const block = buildingBlocks[selected]
  const Icon = block.icon
  return <div className="workbench sdk-workbench"><div className="workbench-toolbar"><span><span className="window-dot"/><span className="window-dot"/><span className="window-dot"/></span><span><Terminal size={14}/> route_support.ts</span><span className="canvas-status"><span className="live-dot"/> INTERACTIVE EXAMPLE</span></div><div className="workbench-canvas"><div className="canvas-problem"><span className="mono-label">THE PROBLEM</span><h3>“How would you send every support ticket <span>to the right team?</span>”</h3><span className="problem-constraint">“I was charged twice.” → Billing. “I can’t log in.” → Account.</span></div><div className="pipeline-stem"/><div className="pipeline-label">DIFFERENT JOBS. DIFFERENT FUNCTIONS. YOUR CODE CONNECTS THEM.</div><div className="block-pipeline">{buildingBlocks.map((item, i) => {const BlockIcon=item.icon;return <div className="pipeline-slot" key={item.name}><button type="button" className={`pipeline-block sdk-block ${selected===i?'selected':''}`} style={blockStyle(item.id)} onClick={()=>setSelected(i)} aria-pressed={selected===i} aria-controls="block-insight"><span className="block-number">0{i+1}</span><BlockIcon size={24} strokeWidth={1.6}/><strong>{item.name}</strong><small>{item.use}</small></button>{i<buildingBlocks.length-1&&<span className="block-plus" aria-hidden="true">+</span>}</div>})}</div><div className="canvas-hint"><span>↑</span> Pick a block. See the code. Click a colored function to explore.</div></div><div className="block-insight" id="block-insight"><div className="insight-explanation" aria-live="polite" aria-atomic="true"><div className="insight-icon" style={blockStyle(block.id)}><Icon size={20}/></div><div className="insight-copy"><strong>{block.question}</strong><p>{block.description}</p>{block.id&&<PrimitiveLink id={block.id}/>}</div></div><PseudoCode code={block.code} compact/></div><div className="workbench-bottom"><span><Check size={14}/> SOFTWARE FIRST. AI WHERE IT HELPS.</span><Link to="/problems/route-support-tickets">Open the full breakdown <ArrowRight size={14}/></Link></div></div>
}

function ToolTile({icon:Icon,name,id}:{icon:typeof Braces;name?:string;id?:PrimitiveId}){const content=<><Icon size={25} strokeWidth={1.5}/><span>{id?<PrimitiveName id={id}/>:name}</span>{id&&<ArrowUpRight size={16}/>}</>;return id?<Link className="tool-tile sdk-tile" style={blockStyle(id)} to={`/primitives/${id}`}>{content}</Link>:<div className="tool-tile">{content}</div>}
function LandingProblem({slug,number,category,icon:Icon,title,functions:ids,question}:{slug:string;number:string;category:string;icon:typeof Braces;title:string;functions:PrimitiveId[];question:string}){return <Link to={`/problems/${slug}`} className="landing-problem-card"><div className="landing-card-top"><span className="mono-label">{category}</span><span className="mono-label muted">/{number}</span></div><div className="problem-card-icon"><Icon size={30} strokeWidth={1.3}/></div><h3>{title}</h3><div className="landing-card-blocks">{ids.map(id=><PrimitiveName key={id} id={id}/>)}</div><div className="landing-card-bottom"><span>{question}</span><ArrowRight size={18}/></div></Link>}
function MethodStep({number,title,text,detail}:{number:string;title:string;text:string;detail:string}){return <article className="method-step"><span className="method-number">{number}</span><div><h3>{title}</h3><p>{text}</p><code>{detail}</code></div><ChevronRight size={17}/></article>}

export function ProblemsPage(){const cats=['All',...new Set(problems.map(p=>p.category))];const [cat,setCat]=useState('All');const list=useMemo(()=>cat==='All'?problems:problems.filter(p=>p.category===cat),[cat]);return <Page><SEO title="Problems" description="Read TypeScript pseudo-programs for real engineering problems and compare AI approaches."/><section className="page-hero shell"><div className="eyebrow">PROBLEM LIBRARY / {String(problems.length).padStart(2,'0')}</div><h1>Start with the problem,<br/><em>not the model.</em></h1><p>Real engineering questions. Small TypeScript programs. The trade-offs that decide what you should actually build.</p></section><section className="shell library"><div className="filters" aria-label="Filter by category">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div>{list.length?<ProblemList problems={list}/>:<div className="empty">No problems in this category yet.</div>}</section></Page>}

export function ProblemDetailPage(){const {slug}=useParams();const p=problemBySlug(slug||'');if(!p)return <Navigate to="/problems" replace/>;const ids=[...new Set(p.approaches.flatMap(a=>a.primitives))];return <Page><SEO title={p.title} description={p.description}/><article className="problem-detail"><header className="detail-hero shell"><Link className="back-link" to="/problems">← All problems</Link><div className="card-meta"><span>{p.category}</span><span>{p.difficulty}</span></div><h1>{p.title}</h1><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>#{t}</span>)}</div></header><section className="think-strip"><div className="shell"><div><span>BEFORE YOU SCROLL</span><h2>Sketch the program first.</h2></div><p>What can ordinary code already do? Where is the input ambiguous? Below, colored functions are the AI capabilities. Helpers like route() and validateInvoice() are regular application code.</p></div></section><section className="shell approaches-wrap"><div className="section-heading"><div><div className="eyebrow">POSSIBLE APPROACHES</div><h2>Same problem.<br/>Different programs.</h2></div><span className="count">{p.approaches.length} alternatives</span></div><div className="pseudo-disclaimer"><Code2 size={17}/><p>Illustrative TypeScript, not runnable SDK code. Schemas, indexes, and ordinary helpers are assumed. Model calls are async; thresholds must be evaluated on your data.</p></div><div>{p.approaches.map((a,i)=><ApproachSection key={a.title} number={i+1} {...a}/>)}</div></section>{ids.length>0&&<section className="shell used-section"><div className="eyebrow">FUNCTIONS IN THIS PROBLEM</div><div className="approach-functions">{ids.map(id=><PrimitiveLink key={id} id={id}/>)}</div></section>}</article></Page>}

export function PrimitivesPage(){return <Page><SEO title="AI function reference" description="An SDK-shaped mental model for applying AI: askCheap, askSmart, classify, extract, score, embed, search, rerank, inspect, call, and evaluate."/><section className="page-hero shell function-library-hero"><div className="eyebrow">THE AI FUNCTION REFERENCE / {primitives.length}</div><h1>AI, shaped like<br/><em>the code you write.</em></h1><p>Small capabilities. Clear inputs and outputs. Learn what each function does, when it earns its place, and what your code still needs to own.</p><div className="pseudo-disclaimer"><Code2 size={17}/><p>A pseudo-SDK for thinking, not a library to install. Each color follows its function from the reference into every program.</p></div></section><section className="shell function-library"><FunctionLegend/><div className="function-grid">{primitives.map(p=><PrimitiveCard key={p.id} primitive={p}/>)}</div><div className="composition-example"><div><div className="eyebrow">COMPOSITION, NOT MAGIC</div><h2>Two calls.<br/>One useful pattern.</h2><p>Search by meaning, then answer from the evidence. Often called RAG. No special rag() function needed.</p></div><PseudoCode code={'const sources = await search(await embed(question), {\n  index: authorizedDocs, limit: 5\n});\n\nconst answer = await askSmart(\n  "Answer only from these sources. Cite them.",\n  { context: { question, sources } }\n);\n\nshowAnswerWithSources(answer, sources);'}/></div></section></Page>}

export function PrimitiveDetailPage(){
  const {id}=useParams()
  if(id && Object.prototype.hasOwnProperty.call(primitiveAliases, id)) return <Navigate to={`/primitives/${primitiveAliases[id]}`} replace/>
  const p=primitiveById(id||'')
  if(!p)return <Navigate to="/primitives" replace/>
  const related=problems.filter(problem=>problem.approaches.some(a=>a.primitives.includes(p.id)))
  const companions=primitives.filter(other=>other.id!==p.id&&p.exampleCode.includes(`${other.id}(`))
  return <Page><SEO title={`${p.name} — function reference`} description={p.short}/><article className="shell function-doc"><aside className="function-sidebar"><Link className="back-link" to="/primitives">← Function reference</Link><span className="eyebrow">T/AI PSEUDO-SDK</span><nav aria-label="AI functions">{primitives.map(fn=><NavLink key={fn.id} to={`/primitives/${fn.id}`}><PrimitiveName id={fn.id}/></NavLink>)}</nav><p>Not an executable SDK.<br/>A mental model for building.</p></aside><div className="function-doc-body"><header className="function-doc-header" style={blockStyle(p.id)}><div className="eyebrow"><span className="function-swatch"/>{p.capability}</div><h1>{p.name}</h1><p>{p.short}</p></header><PrimitiveDiagram primitive={p}/><section className="function-model"><div className="eyebrow">THE MENTAL MODEL</div><p>{p.mentalModel}</p></section><PseudoCode code={`declare function ${p.signature};`} label="FUNCTION SIGNATURE"/><section className="function-contract"><h2>What goes in</h2><dl>{p.parameters.map(param=><div key={param.name}><dt><code>{param.name}</code><span>{param.type}</span></dt><dd>{param.description}</dd></div>)}</dl><h2>What comes back</h2><p>{p.returns}</p></section><section className="function-example"><PseudoCode code={p.exampleCode}/><div className="example-result"><span>ILLUSTRATIVE RESULT</span><pre tabIndex={0} aria-label="Illustrative return value"><code>{p.exampleResult}</code></pre></div>{companions.length>0&&<div className="compose-with"><span>COMPOSES WITH</span>{companions.map(fn=><PrimitiveLink key={fn.id} id={fn.id}/>)}</div>}</section><div className="function-use-grid"><section><h2><Check size={18}/> Reach for it when</h2><ul>{p.useful.map(x=><li key={x}>{x}</li>)}</ul></section><section><h2><X size={18}/> Leave it out when</h2><ul>{p.notUseful.map(x=><li key={x}>{x}</li>)}</ul></section></div><aside className="function-caution"><span>THE PART YOUR CODE OWNS</span><p>{p.caution}</p></aside><section className="function-providers"><div className="eyebrow">POSSIBLE IMPLEMENTATIONS</div><h2>Different engines. Same capability.</h2><ul>{p.providers.map(provider=><li key={provider}>{provider}</li>)}</ul><p>Examples, not endorsements or a required dependency list. Model families and capabilities change. Benchmark the actual implementation against your latency, cost, and quality requirements.</p></section><section className="function-related"><div className="eyebrow">READ IT IN A REAL PROGRAM</div><h2>Used in these problems</h2>{related.length?<ProblemList problems={related}/>:<div className="empty">More problem examples are coming soon.</div>}</section></div></article></Page>
}

export function WaitlistPage(){return <Page><SEO title="Join the waitlist" description="Get early access to Think Like an AI Engineer."/><section className="waitlist-page shell"><div className="waitlist-copy"><div className="eyebrow">EARLY ACCESS</div><h1>Learn what to build.<br/><em>And what not to.</em></h1><p>We're building a practical field guide for experienced engineers working out where AI actually belongs.</p><ul><li><Check/>New problem breakdowns</li><li><Check/>Code-first AI function explainers</li><li><Check/>Early product access</li></ul></div><div className="form-card"><WaitlistForm/></div></section></Page>}

export function NotFoundPage(){return <Page><section className="not-found shell"><span>404</span><h1>Nothing at this route.</h1><Link className="button" to="/">Back home <ArrowRight size={16}/></Link></section></Page>}
