export type PrimitiveId = 'askCheap' | 'askSmart' | 'classify' | 'extract' | 'score' | 'embed' | 'search' | 'rerank' | 'inspect' | 'call' | 'evaluate'

export interface Approach { title: string; summary: string; code: string; takeaway: string; tradeoff: string; measure: string; primitives: PrimitiveId[] }
export interface Problem { slug: string; title: string; description: string; category: string; difficulty: 'Foundational' | 'Intermediate' | 'Advanced'; tags: string[]; approaches: Approach[] }
export interface Primitive {
  id: PrimitiveId; name: string; capability: string; short: string; color: string; tint: string
  signature: string; parameters: { name: string; type: string; description: string }[]; returns: string
  input: string; output: string; mentalModel: string; useful: string[]; notUseful: string[]
  caution: string; providers: string[]; exampleCode: string; exampleResult: string
}

export const primitives: Primitive[] = [
  {
    id: 'askCheap', name: 'askCheap()', capability: 'Fast language generation', color: '#367047', tint: '#e6f0e7',
    short: 'Give a small model a narrow language task. Get text back, quickly and cheaply.',
    signature: 'askCheap(\n  prompt: string,\n  options?: { context?: unknown }\n): Promise<string>',
    parameters: [{ name: 'prompt', type: 'string', description: 'One clear task with an explicit output format.' }, { name: 'options.context', type: 'unknown · optional', description: 'The facts or source text the answer must use.' }],
    returns: 'Generated text. Not a verified fact or a guaranteed correct answer.', input: 'A narrow prompt + source text', output: 'A short text response',
    mentalModel: 'A fast text-in, text-out helper. Great for bounded transformations; not the place to spend your hardest reasoning problem. “Cheap” is a cost and latency tier, not a guarantee.',
    useful: ['Drafting a short reply from supplied facts', 'Summarizing a small document', 'Rewriting text into a consistent tone'],
    notUseful: ['Complex, multi-step reasoning', 'Exact calculations or authoritative facts', 'Typed fields that need extract() instead'],
    caution: 'Measure quality on your own cases. A smaller model can be the wrong economy if retries or mistakes cost more than you save.',
    providers: ['Anthropic · Claude Haiku family', 'Google · Gemini Flash family', 'OpenAI · smaller language models'],
    exampleCode: 'const draft = await askCheap(\n  "Write a friendly, two-sentence reply.",\n  { context: { issue: "refund", policy: refundPolicy } }\n);\n\nshowDraftToAgent(draft);',
    exampleResult: '"I can help with your refund request. Let’s check your order against our refund policy."',
  },
  {
    id: 'askSmart', name: 'askSmart()', capability: 'Deeper language reasoning', color: '#79539d', tint: '#eee6f6',
    short: 'Spend more reasoning on the ambiguous cases. Request text or a typed suggestion.',
    signature: 'askSmart<T = string>(\n  prompt: string,\n  options?: AskOptions<T>\n): Promise<T>',
    parameters: [{ name: 'prompt', type: 'string', description: 'The question or decision to reason about.' }, { name: 'options.context', type: 'unknown · optional', description: 'Relevant evidence. Retrieved text is data, not trusted instructions.' }, { name: 'options.schema', type: 'Schema<T> · optional', description: 'An output contract; without it, return text. Validate either way.' }, { name: 'options.tools', type: 'ToolDefinition[] · optional', description: 'Allowed tool descriptions for suggesting a next action. This does not execute tools.' }],
    returns: 'Text by default, or a schema-shaped suggestion. Neither is proof of correctness.', input: 'A hard question + bounded evidence', output: 'An answer or typed proposal',
    mentalModel: 'A slower reasoning helper, not an oracle. Keep it off the obvious path. Your code supplies the evidence, checks the result, and owns the final decision.',
    useful: ['Interpreting ambiguous requests', 'Explaining retrieved code or incident evidence', 'Proposing a next step in a bounded workflow'],
    notUseful: ['Every item in a high-volume pipeline', 'Authorizing payments or destructive actions', 'Retrieving fresh facts without a source'],
    caution: 'Bigger models still hallucinate. Treat tool suggestions as untrusted input; enforce schemas, allowlists, permissions, and call limits in ordinary code.',
    providers: ['Anthropic · Claude Sonnet / Opus families', 'OpenAI · reasoning-capable models', 'Google · Gemini Pro family'],
    exampleCode: 'const decision = await askSmart(\n  "Choose a support queue. Explain the evidence.",\n  { context: ticket.text, schema: routingSchema }\n);\n\nif (isAllowedQueue(decision.queue)) {\n  suggestRoute(ticket, decision);\n}',
    exampleResult: '{ queue: "billing", reason: "The customer describes a duplicate charge." }',
  },
  {
    id: 'classify', name: 'classify()', capability: 'AI classification', color: '#326a9e', tint: '#e5eef8',
    short: 'Choose from a known set of categories. Return a label and a confidence score.',
    signature: 'classify(\n  input: string,\n  categories: string[]\n): Promise<{\n  label: string;\n  confidence: number;\n}>',
    parameters: [{ name: 'input', type: 'string', description: 'The text or features you want to categorize.' }, { name: 'categories', type: 'string[]', description: 'Allowed labels. Include an “other” option for unfamiliar inputs.' }],
    returns: '{ label, confidence } — a permitted category and an implementation-specific score from 0 to 1.', input: '“I was charged twice” + queue names', output: '{ label: "billing", confidence: 0.94 }',
    mentalModel: 'A fuzzy switch statement. Unlike if/else, it can recognize meaning across different wording. The confidence field tells your code when to consider a fallback—not a guaranteed probability of being right.',
    useful: ['Support routing and intent detection', 'Repeated decisions with stable categories', 'A cheap first pass before expensive reasoning'],
    notUseful: ['Open-ended answers or explanations', 'Categories with no clear boundaries', 'Exact rules already expressed by structured fields'],
    caution: 'Evaluate confidence bands on labeled examples. Every threshold on this site is illustrative; calibrate it before auto-routing real traffic.',
    providers: ['A classifier trained on your labeled data', 'An embedding-based classifier', 'A language model with constrained labels'],
    exampleCode: 'const intent = await classify(ticket.text, [\n  "billing", "technical", "account", "other"\n]);\n\nif (intent.label !== "other" && intent.confidence >= 0.8) {\n  route(ticket, intent.label);\n} else {\n  queueForReview(ticket);\n}',
    exampleResult: '{ label: "billing", confidence: 0.94 }',
  },
  {
    id: 'extract', name: 'extract()', capability: 'Structured extraction', color: '#a05f24', tint: '#f6eadb',
    short: 'Turn messy input into schema-shaped data your code can validate.',
    signature: 'extract<T>(\n  input: string | Document,\n  schema: Schema<T>,\n  options?: ExtractOptions\n): Promise<T>',
    parameters: [{ name: 'input', type: 'string | Document', description: 'Source text, a PDF, or a scanned document with the right model adapter.' }, { name: 'schema', type: 'Schema<T>', description: 'Field names, types, and nullable values for missing information.' }, { name: 'options.tier', type: '"cheap" | "smart" · optional', description: 'Select a model tier. A higher tier is not a substitute for validation.' }],
    returns: 'An object shaped like your schema. A valid shape does not mean the values are true.', input: 'A messy invoice + field schema', output: '{ vendor: "Acme", total: 120, currency: "USD" }',
    mentalModel: 'A parser for inputs without a reliable grammar. Give it a contract, then handle its output the way you handle any untrusted API response. Missing fields should be null, not invented.',
    useful: ['Invoices, contracts, and forms', 'Turning free text into typed fields', 'Mixed document layouts without stable templates'],
    notUseful: ['Clean JSON or CSV you can parse directly', 'Recalculating totals or validating business rules', 'Fields not actually present in the source'],
    caution: 'Validate dates and identifiers, recalculate totals in code, and compare important values to source evidence. Extraction is not approval.',
    providers: ['Language models with structured output support', 'Vision-capable models for scanned documents', 'Google Document AI / Azure AI Document Intelligence adapters'],
    exampleCode: 'const fields = await extract(invoice, invoiceSchema);\nconst checks = validateInvoice(fields);\n\nif (checks.valid && matchesSource(fields, invoice)) {\n  saveDraft(fields);\n} else {\n  queueForReview({ invoice, fields, checks });\n}',
    exampleResult: '{ vendor: "Acme", invoiceNumber: "INV-1042", total: 120, currency: "USD" }',
  },
  {
    id: 'score', name: 'score()', capability: 'AI scoring', color: '#9b4f78', tint: '#f4e4ed',
    short: 'Judge an input against explicit criteria. Return a score and supporting evidence.',
    signature: 'score(\n  input: unknown,\n  criteria: string[]\n): Promise<{\n  value: number;\n  evidence: string[];\n}>',
    parameters: [{ name: 'input', type: 'unknown', description: 'A candidate, pair of records, or response to assess.' }, { name: 'criteria', type: 'string[]', description: 'A concrete rubric. Define what a high or low score means.' }],
    returns: '{ value, evidence } — a rubric score from 0 to 1 and the signals behind it.', input: 'Two records + matching criteria', output: '{ value: 0.91, evidence: ["same identifier"] }',
    mentalModel: 'A fuzzy comparison function. Use it to rank or triage, not to turn judgment into fake certainty. It can be a learned scorer or a model applying a rubric; those need different calibration.',
    useful: ['Ranking candidate matches', 'Prioritizing a review queue', 'Assessing a draft against a clear quality rubric'],
    notUseful: ['A factual probability without calibration', 'Replacing deterministic eligibility checks', 'Automatic irreversible merges based on one score'],
    caution: 'Test against human-labeled pairs. A score of 0.9 is not automatically a 90% likelihood, and model-written evidence can be wrong.',
    providers: ['A trained pairwise scoring model', 'A cross-encoder model', 'A language model with a fixed evaluation rubric'],
    exampleCode: 'const match = await score([record, candidate], [\n  "same legal identity", "matching identifiers"\n]);\n\nif (match.value > 0.9) {\n  proposeMerge(record, candidate, match.evidence);\n}',
    exampleResult: '{ value: 0.91, evidence: ["same tax identifier", "address differs only in formatting"] }',
  },
  {
    id: 'embed', name: 'embed()', capability: 'Meaning as a vector', color: '#6553ab', tint: '#eae6f8',
    short: 'Turn text into numbers so similar meanings can be found near each other.',
    signature: 'embed(\n  text: string\n): Promise<number[]>',
    parameters: [{ name: 'text', type: 'string', description: 'The query or content to represent. Use the same model for both sides of a search.' }],
    returns: 'A vector of numbers. Its dimensions depend on the embedding model.', input: '“Where do we retry failed jobs?”', output: '[0.12, -0.81, 0.34, …]',
    mentalModel: 'A coordinate for meaning. It does not answer the question; it makes similarity searchable. Think of it as a feature encoder you can use with indexes, clustering, or matching.',
    useful: ['Semantic search and nearest-neighbor retrieval', 'Finding similar support cases', 'Candidate generation for duplicate detection'],
    notUseful: ['Exact ID or amount matching', 'Generating text', 'Proving that two records are identical'],
    caution: 'Embeddings from different models are not interchangeable. Re-index when you change the model, and keep exact filters alongside semantic similarity.',
    providers: ['OpenAI · text embedding models', 'Google · text embedding models', 'Cohere Embed / local sentence-transformer models'],
    exampleCode: 'const vector = await embed("Where do we retry failed jobs?");\nconst hits = await search(vector, {\n  index: codeIndex, limit: 10\n});\n\nshowResults(hits);',
    exampleResult: '[0.12, -0.81, 0.34, 0.07, …]',
  },
  {
    id: 'search', name: 'search()', capability: 'Vector retrieval', color: '#20777b', tint: '#dff0ef',
    short: 'Find nearby items in an index. Return candidates, not an answer.',
    signature: 'search<T>(\n  vector: number[],\n  options: SearchOptions<T>\n): Promise<SearchHit<T>[]>',
    parameters: [{ name: 'vector', type: 'number[]', description: 'A query encoded with the same embedding model used by the index.' }, { name: 'options.index', type: 'VectorIndex<T>', description: 'An already-built index. Ingestion, chunking, and permissions are your code’s responsibility.' }, { name: 'options.limit', type: 'number', description: 'How many candidates to retrieve.' }, { name: 'options.filter', type: 'Record<string, unknown> · optional', description: 'Hard metadata constraints such as tenant, currency, or verified status.' }],
    returns: 'SearchHit<T>[] — each hit has { item, similarity }. Similarity is not factual correctness.', input: 'Query vector + authorized index', output: '[{ item: retryJob, similarity: 0.89 }]',
    mentalModel: 'An index lookup by meaning instead of an exact key. The AI work happens in embed(); the search itself is often ordinary vector-database infrastructure. A plausible neighbor is only a candidate.',
    useful: ['Finding code, documents, or similar tickets', 'Selecting context before askSmart()', 'Reducing millions of records to a small candidate set'],
    notUseful: ['Exact symbol lookup that keyword search handles', 'Answering questions without reading the results', 'Bypassing tenant or access-control filters'],
    caution: 'Apply authorization and hard constraints before returning results. Test retrieval recall independently from any generated answer.',
    providers: ['Postgres + pgvector / Supabase', 'Pinecone / Qdrant / Weaviate', 'An in-process vector index'],
    exampleCode: 'const hits = await search(await embed(question), {\n  index: docsIndex,\n  limit: 8,\n  filter: { tenantId: user.tenantId }\n});\n\nshowSources(hits.map(hit => hit.item));',
    exampleResult: '[{ item: { id: "retryJob", path: "jobs/retry.ts" }, similarity: 0.89 }]',
  },
  {
    id: 'rerank', name: 'rerank()', capability: 'Candidate reranking', color: '#95691d', tint: '#f5edcf',
    short: 'Take a short candidate list and put the most relevant items first.',
    signature: 'rerank<T>(\n  query: string,\n  candidates: T[]\n): Promise<{\n  item: T;\n  relevance: number;\n}[]>',
    parameters: [{ name: 'query', type: 'string', description: 'The original user question, not just its vector.' }, { name: 'candidates', type: 'T[]', description: 'A small set returned by cheaper retrieval. Include the text to compare.' }],
    returns: 'Candidates ordered by relevance, with a score for each. No new evidence is created.', input: 'A question + 20 candidate passages', output: 'The same passages, in a better order',
    mentalModel: 'A smarter sort over a small list. Retrieve broadly first; then spend extra computation comparing each candidate with the actual query. It cannot recover evidence missing from the candidate set.',
    useful: ['Improving top code or document search results', 'Ordering merged keyword and vector candidates', 'Choosing a smaller context window'],
    notUseful: ['Scoring your entire database one item at a time', 'Fixing poor ingestion or missing candidates', 'Generating the final answer'],
    caution: 'Measure top-k relevance and latency. Reranking adds a model call and only helps if the first retrieval pass finds useful candidates.',
    providers: ['Cohere Rerank', 'Local cross-encoder rerankers', 'A language-model-based reranker'],
    exampleCode: 'const hits = await search(await embed(query), {\n  index: codeIndex, limit: 20\n});\nconst ranked = await rerank(query, hits.map(hit => hit.item));\n\nshowResults(ranked.slice(0, 5));',
    exampleResult: '[{ item: { path: "jobs/retry.ts" }, relevance: 0.96 }, …]',
  },
  {
    id: 'inspect', name: 'inspect()', capability: 'Multimodal interpretation', color: '#ac533e', tint: '#f8e5df',
    short: 'Ask a question about an image, scan, or supported media input.',
    signature: 'inspect(\n  input: Image | Document,\n  prompt: string\n): Promise<string>',
    parameters: [{ name: 'input', type: 'Image | Document', description: 'A screenshot, scan, or document supported by the selected model.' }, { name: 'prompt', type: 'string', description: 'What to look for. Ask for visible evidence and let the model say it cannot read something.' }],
    returns: 'A textual observation. It may miss details or misread small text.', input: 'An invoice scan + a visual question', output: 'An observation about visible layout or text',
    mentalModel: 'A language model with eyes, not a pixel-perfect measuring instrument. Useful when layout carries information that plain extracted text loses.',
    useful: ['Understanding an unfamiliar scanned layout', 'Reading mixed text and image context', 'Describing a screenshot for a review workflow'],
    notUseful: ['Clean machine-readable documents', 'Precise spatial measurements', 'Typed fields better requested with extract()'],
    caution: 'Verify visual observations against the source. Blurred scans, tiny text, and unsupported formats need explicit failure handling.',
    providers: ['OpenAI · vision-capable models', 'Anthropic · vision-capable Claude models', 'Google · multimodal Gemini models'],
    exampleCode: 'const observation = await inspect(invoiceScan,\n  "Describe the totals section. Flag unreadable text."\n);\n\nshowObservationBesideSource(observation, invoiceScan);',
    exampleResult: '"The total appears in the bottom-right box. The invoice number is blurred and cannot be read reliably."',
  },
  {
    id: 'call', name: 'call()', capability: 'Controlled tool execution', color: '#4d7184', tint: '#e4edf1',
    short: 'Execute an allowed tool with typed arguments. Your code—not the model—owns access.',
    signature: 'call<TArgs, TResult>(\n  tool: Tool<TArgs, TResult>,\n  args: TArgs\n): Promise<TResult>',
    parameters: [{ name: 'tool', type: 'Tool<TArgs, TResult>', description: 'A registered, permission-checked operation. Prefer bounded read-only tools.' }, { name: 'args', type: 'TArgs', description: 'Arguments validated against the tool schema. Never trust a model’s proposal directly.' }],
    returns: 'The tool’s actual result. This function is an execution boundary, not an AI prediction.', input: 'An allowed tool + validated arguments', output: 'The real API or database result',
    mentalModel: 'A narrow bridge from a model suggestion to ordinary software. askSmart() can propose what to call; your code decides whether it is allowed and actually invokes it. Calling a fixed API does not require an agent.',
    useful: ['Read-only incident and code exploration', 'Connecting language workflows to existing APIs', 'Inspecting a bounded sequence of tool results'],
    notUseful: ['Unrestricted shell or database access', 'Irreversible actions without explicit approval', 'Simple API calls that need no model judgment'],
    caution: 'Enforce schemas, permissions, timeouts, result limits, and maximum call counts outside the model. Obtain approval before any real-world or destructive action.',
    providers: ['Your typed HTTP / database adapters', 'Permissioned MCP tools', 'Model tool-calling output, followed by your executor'],
    exampleCode: 'const result = await call(readOnlyTools.findReferences, {\n  symbol: "retryJob",\n  repository: authorizedRepo,\n  limit: 20\n});\n\nshowReferences(result);',
    exampleResult: '[{ path: "worker.ts", line: 42 }, { path: "retry.test.ts", line: 18 }]',
  },
  {
    id: 'evaluate', name: 'evaluate()', capability: 'Evidence from test cases', color: '#687b2d', tint: '#eaf0d7',
    short: 'Run an approach against known cases. Measure whether it actually works.',
    signature: 'evaluate(\n  cases: TestCase[],\n  predict: Predictor,\n  metric: Metric\n): Promise<EvaluationReport>',
    parameters: [{ name: 'cases', type: 'TestCase[]', description: 'Representative inputs with independently checked expected outcomes.' }, { name: 'predict', type: 'Predictor', description: 'The function or full pipeline being tested.' }, { name: 'metric', type: 'Metric', description: 'A deterministic measurement such as label accuracy, recall, or field accuracy.' }],
    returns: 'An evaluation report containing sampleCount, metricValue, and failures.', input: 'Labeled cases + a candidate pipeline', output: '{ sampleCount: 500, metricValue: 0.94, failures: […] }',
    mentalModel: 'A test harness for fuzzy behavior. Ordinary assertions still handle schemas and invariants; evaluate() measures quality across realistic cases. It is not itself necessarily AI.',
    useful: ['Comparing model tiers or retrieval approaches', 'Calibrating confidence thresholds', 'Tracking regressions on high-cost failure cases'],
    notUseful: ['Proving production quality from a tiny demo', 'Using only another model’s opinion as ground truth', 'A one-time launch check with no monitoring'],
    caution: 'Keep evaluation cases separate from tuning data. Report coverage, failure slices, latency, and cost—not just a single average score.',
    providers: ['Your TypeScript test harness', 'Promptfoo / Braintrust / LangSmith', 'Human-labeled cases with deterministic metrics'],
    exampleCode: 'const report = await evaluate(\n  labeledTickets,\n  ticket => classify(ticket.text, queues),\n  labelAccuracy\n);\n\ninspectFailures(report.failures);',
    exampleResult: '{ sampleCount: 500, metricValue: 0.94, failures: […] }',
  },
]

export const problems: Problem[] = [
  { slug: 'route-support-tickets', title: 'How would you send every support ticket to the right team?', description: '“I was charged twice.” “I can’t log in.” “Your API is down.” Route 100K messages to billing, account, or technical support without sending everything to an expensive model.', category: 'Operations', difficulty: 'Foundational', tags: ['classification', 'routing', 'cost'], approaches: [
    { title: 'Use the information you already have', summary: 'A structured form field can make the decision without any AI.', primitives: [], code: 'const queues = ["billing", "technical", "account"];\n\nif (queues.includes(ticket.selectedTopic)) {\n  route(ticket, ticket.selectedTopic);\n} else {\n  queueForReview(ticket);\n}', takeaway: 'A selected topic is a reliable signal. You do not need a model to rediscover it.', tradeoff: 'Fast and predictable, but free-text messages still need a fallback.', measure: 'Unresolved rate and incorrect form selections.' },
    { title: 'Classify the easy ones. Reason about the rest.', summary: 'A fuzzy switch statement, with a more capable model only on the uncertain path.', primitives: ['classify', 'askSmart'], code: 'const queues = ["billing", "technical", "account", "other"];\nconst intent = await classify(ticket.text, queues);\n\nif (intent.label !== "other" && intent.confidence >= 0.8) {\n  route(ticket, intent.label);\n} else {\n  const suggestion = await askSmart(\n    "Choose a queue and explain why.",\n    { context: ticket.text, schema: routingSchema }\n  );\n  queueForReview({ ticket, suggestion });\n}', takeaway: 'AI handles the wording. Your code owns the threshold, routing, and fallback.', tradeoff: 'The 0.8 cutoff is illustrative. Calibrate it on labeled tickets; review model suggestions before trusting them.', measure: 'Per-queue precision, fallback rate, cost per ticket, and latency.' },
    { title: 'Look for a ticket you have already solved', summary: 'Retrieve verified precedents instead of retraining for every label change.', primitives: ['embed', 'search', 'askCheap'], code: 'const hits = await search(await embed(ticket.text), {\n  index: resolvedTickets,\n  limit: 3,\n  filter: { tenantId: ticket.tenantId, verified: true }\n});\n\nif (hits.length > 0) {\n  const explanation = await askCheap(\n    "Summarize how these similar tickets were routed.",\n    { context: hits.map(hit => hit.item) }\n  );\n  showToAgent({ ticket, hits, explanation });\n} else {\n  queueForReview(ticket);\n}', takeaway: 'Similarity finds precedents. An operator checks whether the precedent actually applies.', tradeoff: 'Adapts quickly to new queues, but stale or incorrectly resolved tickets make poor evidence.', measure: 'Relevant precedent recall and agent acceptance rate.' },
  ] },
  { slug: 'reconcile-bank-transactions', title: 'How would you match 1M bank payments to your ledger?', description: 'Pair noisy bank descriptions with the correct ledger entry. Keep amounts and currencies exact, preserve an audit trail, and review uncertainty.', category: 'Fintech', difficulty: 'Advanced', tags: ['matching', 'high-volume', 'auditability'], approaches: [
    { title: 'Exact identifiers before fuzzy judgment', summary: 'Ordinary code handles clear matches and records why they were accepted.', primitives: [], code: 'for (const payment of bankPayments) {\n  const entry = ledger.findByReference(payment.reference);\n\n  if (entry && sameAmountAndCurrency(payment, entry)\n      && !alreadyMatched(entry)) {\n    acceptMatch(payment, entry, "exact reference");\n  } else {\n    queueForReview(payment);\n  }\n}', takeaway: 'The structured portion of the problem is a database lookup, not an AI task.', tradeoff: 'Excellent precision; descriptions with missing references remain unresolved.', measure: 'Exact-match precision and unmatched volume.' },
    { title: 'Find candidates by meaning. Verify in code.', summary: 'Use semantic retrieval for inconsistent descriptions, not for the final accounting decision.', primitives: ['embed', 'search'], code: 'const hits = await search(await embed(payment.description), {\n  index: ledgerIndex,\n  limit: 5,\n  filter: {\n    accountId: payment.accountId,\n    amount: payment.amount,\n    currency: payment.currency,\n    unmatched: true\n  }\n});\n\nconst candidates = hits.map(hit => hit.item)\n  .filter(entry => withinDateWindow(payment, entry));\n\nqueueForReview({ payment, candidates });', takeaway: 'embed() broadens candidate discovery. Amounts, access, dates, and one-to-one matching stay deterministic.', tradeoff: 'Similar descriptions are not proof of a match. The example proposes candidates rather than posting entries.', measure: 'Candidate recall and review workload.' },
    { title: 'Spend reasoning only on ambiguous pairs', summary: 'Ask for a typed proposal with evidence, then leave ledger changes to a reviewer.', primitives: ['embed', 'search', 'askSmart'], code: 'const hits = await search(await embed(payment.description), {\n  index: ledgerIndex, limit: 3,\n  filter: { accountId: payment.accountId, currency: payment.currency }\n});\nconst candidates = hits.map(hit => hit.item)\n  .filter(entry => validAccountingCandidate(payment, entry));\n\nif (candidates.length > 0) {\n  const proposal = await askSmart(\n    "Suggest a match from these candidates, or abstain.",\n    { context: { payment, candidates }, schema: matchSchema }\n  );\n  queueForReview({ payment, candidates, proposal });\n} else {\n  queueForReview(payment);\n}', takeaway: 'A language model interprets the messy description. It does not get permission to mutate the ledger.', tradeoff: 'More helpful explanations, at higher latency and cost. Validate any proposed ID against the candidate set.', measure: 'Proposal precision, abstention rate, and reviewer corrections.' },
  ] },
  { slug: 'natural-language-code-search', title: 'How would you find code by what it does?', description: 'Find “the code that retries failed jobs” even when the repository uses different names. Respect repository access and show the underlying source.', category: 'Developer Tools', difficulty: 'Intermediate', tags: ['search', 'code', 'retrieval'], approaches: [
    { title: 'Combine exact search with search by meaning', summary: 'Keep symbol search. Add vector candidates, then improve their order.', primitives: ['embed', 'search', 'rerank'], code: 'const exact = keywordSearch(query, authorizedRepo);\nconst semantic = await search(await embed(query), {\n  index: codeIndex, limit: 20,\n  filter: { repository: authorizedRepo }\n});\nconst candidates = deduplicate([\n  ...exact, ...semantic.map(hit => hit.item)\n]);\nconst ranked = await rerank(query, candidates);\n\nshowResults(ranked.slice(0, 5));', takeaway: 'A precise function name wants keyword search. A description of behavior wants semantic search. Neither replaces the other.', tradeoff: 'Extra indexing and a reranking call. Chunk code by symbols and preserve file paths.', measure: 'Top-5 relevance, retrieval recall, and search latency.' },
    { title: 'Find the source. Then explain it.', summary: 'An answer is a composition of retrieval and generation, not a mysterious new primitive.', primitives: ['embed', 'search', 'rerank', 'askSmart'], code: 'const hits = await search(await embed(question), {\n  index: codeIndex, limit: 15,\n  filter: { repository: authorizedRepo }\n});\nconst ranked = await rerank(question, hits.map(hit => hit.item));\nconst sources = ranked.slice(0, 5).map(hit => hit.item);\n\nif (sources.length === 0) {\n  showNoEvidence();\n} else {\n  const answer = await askSmart(\n    "Answer from these sources. Cite paths. Say when evidence is missing.",\n    { context: { question, sources } }\n  );\n  showAnswerWithSources(answer, sources);\n}', takeaway: 'This pattern is often called RAG. Here you can see its parts: search(), then askSmart().', tradeoff: 'A polished answer can still be wrong. Opening the original code must be effortless.', measure: 'Source relevance and evidence-supported answer accuracy separately.' },
    { title: 'Follow a call chain with bounded tools', summary: 'A model proposes an inspection step; ordinary code authorizes and executes it.', primitives: ['askSmart', 'call'], code: 'const evidence = [];\n\nfor (let step = 0; step < 4; step++) {\n  const plan = await askSmart(\n    "Suggest the next read-only inspection, or finish.",\n    { context: { question, evidence },\n      tools: readOnlyToolDefinitions, schema: nextStepSchema }\n  );\n  if (plan.done) break;\n\n  const tool = requireAllowedTool(plan.tool, user);\n  const args = validateAndBoundArgs(tool, plan.args);\n  evidence.push(await call(tool, args));\n}\n\nshowExplorationTrace(evidence);', takeaway: 'An “agent” is a loop around reasoning and controlled tool calls. You can design the loop yourself.', tradeoff: 'More latency than direct search. Enforce repository permissions, bounded results, and call limits outside the model.', measure: 'Useful evidence per call, task completion, cost, and permission violations.' },
  ] },
  { slug: 'extract-messy-invoices', title: 'How would you turn messy invoices into clean data?', description: 'Turn PDFs and scans into validated invoice fields. Missing values must stay missing, and model output must never bypass ordinary business checks.', category: 'Documents', difficulty: 'Intermediate', tags: ['extraction', 'documents', 'validation'], approaches: [
    { title: 'A known layout is a parsing problem', summary: 'Try templates and existing OCR before introducing a model.', primitives: [], code: 'const text = await readPdfTextOrOcr(invoice);\nconst template = findVendorTemplate(text);\n\nif (template) {\n  const fields = parseWithTemplate(text, template);\n  const checks = validateInvoice(fields);\n  if (checks.valid) saveDraft(fields);\n  else queueForReview({ invoice, fields, checks });\n} else {\n  queueForReview(invoice);\n}', takeaway: 'Stable templates and deterministic validators may solve most of the volume. OCR is a separate implementation choice, not automatically an LLM.', tradeoff: 'Low cost for stable vendors; brittle when layouts change.', measure: 'Field accuracy by vendor and unknown-layout rate.' },
    { title: 'Ask for fields, not a paragraph', summary: 'A schema-shaped result is the start of validation, not the end.', primitives: ['extract'], code: 'const invoiceSchema = {\n  vendor: "string | null",\n  invoiceNumber: "string | null",\n  total: "number | null",\n  currency: "string | null",\n  lineItems: "LineItem[]"\n};\nconst fields = await extract(invoice, invoiceSchema);\nconst checks = validateInvoice(fields);\n\nif (checks.valid && matchesSource(fields, invoice)) {\n  saveDraft(fields);\n} else {\n  queueForReview({ invoice, fields, checks });\n}', takeaway: 'extract() handles the messy layout. Code checks arithmetic, required fields, dates, and currencies.', tradeoff: 'The schema notation is illustrative, not a real validator library. A well-typed hallucination is still a hallucination.', measure: 'Field-level accuracy and missing-value correctness against source documents.' },
    { title: 'Escalate only the documents that fail', summary: 'Start with a cheap extraction tier; reserve visual reasoning and stronger models for failures.', primitives: ['extract', 'inspect'], code: 'let fields = await extract(invoice, invoiceSchema, { tier: "cheap" });\n\nif (!validateInvoice(fields).valid) {\n  const observation = await inspect(invoice,\n    "Locate the totals and flag unreadable fields."\n  );\n  fields = await extract(invoice, invoiceSchema, { tier: "smart" });\n  attachReviewEvidence(invoice, observation);\n}\n\nif (validateInvoice(fields).valid && matchesSource(fields, invoice)) {\n  saveDraft(fields);\n} else {\n  queueForReview({ invoice, fields });\n}', takeaway: 'Not every PDF deserves the most expensive model. Difficulty is a routing decision.', tradeoff: 'Two calls on difficult documents. A visual observation is supporting evidence, not a replacement for source verification.', measure: 'Escalation rate, cost per document, and accuracy of high-value fields.' },
  ] },
  { slug: 'detect-duplicate-records', title: 'How would you find duplicate records?', description: 'Find exact and near duplicates despite inconsistent names and incomplete metadata. Similar does not always mean identical, and merging is a high-stakes action.', category: 'Data Systems', difficulty: 'Foundational', tags: ['deduplication', 'similarity', 'quality'], approaches: [
    { title: 'Normalize. Hash. Compare.', summary: 'Remove obvious duplicates with functions you already know.', primitives: [], code: 'const groups = groupBy(records, record =>\n  hash({\n    tenantId: record.tenantId,\n    email: normalizeEmail(record.email),\n    legalId: normalizeIdentifier(record.legalId)\n  })\n);\n\nfor (const group of groups.values()) {\n  if (group.length > 1 && hasCompleteIdentifiers(group)) {\n    proposeDuplicateGroup(group);\n  }\n}', takeaway: 'Exact duplicate detection has no need for language generation.', tradeoff: 'Missing identifiers and genuinely different spellings need a second approach. Do not group incomplete records as confirmed duplicates.', measure: 'Exact-duplicate precision and unresolved pairs.' },
    { title: 'Search for neighbors, then check the fields', summary: 'Meaning finds a candidate set; deterministic constraints prevent careless merges.', primitives: ['embed', 'search'], code: 'const hits = await search(await embed(describeRecord(record)), {\n  index: recordsIndex, limit: 10,\n  filter: { tenantId: record.tenantId }\n});\nconst candidates = hits.map(hit => hit.item)\n  .filter(other => other.id !== record.id)\n  .filter(other => compatibleIdentifiers(record, other));\n\nshowCandidatesForReview(record, candidates);', takeaway: 'embed() and search() are candidate generators, not identity proofs.', tradeoff: 'Boilerplate and common names can be deceptively close in vector space.', measure: 'Candidate recall and false-positive rate on difficult names.' },
    { title: 'Score uncertain pairs. Test before trusting.', summary: 'A matching rubric and evaluation cases turn intuition into measured evidence.', primitives: ['score', 'evaluate'], code: 'const criteria = [\n  "same legal identity", "consistent identifiers", "compatible address"\n];\nconst report = await evaluate(\n  labeledPairs,\n  pair => score(pair, criteria),\n  pairRankingQuality\n);\n\nif (passesQualityGate(report)) {\n  const match = await score([record, candidate], criteria);\n  if (match.value >= 0.9) {\n    proposeMerge(record, candidate, match.evidence);\n  } else {\n    queueForReview({ record, candidate, match });\n  }\n}', takeaway: 'A scoring function helps prioritize. Evaluation determines whether that score earns trust.', tradeoff: 'The threshold is illustrative. Keep merges reviewable and reversible; validate model-written evidence against actual fields.', measure: 'Pair ranking quality, false merges, and accuracy by data slice.' },
  ] },
  { slug: 'investigate-production-logs', title: 'How would you find useful evidence in noisy production logs?', description: 'Turn a noisy incident stream into evidence an engineer can inspect. Help investigate without treating a generated explanation as the root cause.', category: 'Reliability', difficulty: 'Advanced', tags: ['logs', 'incidents', 'tools'], approaches: [
    { title: 'Start with observability, not a chatbot', summary: 'Join the signals you already collect with ordinary queries.', primitives: [], code: 'const errors = groupByFingerprint(logs);\nconst traces = joinByTraceId(errors, traceStore);\nconst deploys = deploymentsDuring(incident.window);\n\nshowIncidentTimeline({\n  errors, traces, deploys,\n  window: incident.window\n});', takeaway: 'Reliable timestamps, joins, and error fingerprints solve known failure modes better than speculative text.', tradeoff: 'A model cannot repair an observability foundation with missing identifiers or inaccessible evidence.', measure: 'Time to relevant trace and signal coverage.' },
    { title: 'Retrieve the runbook. Draft an evidence-based timeline.', summary: 'Use a fast summary for navigation and a reasoning model only for follow-up questions.', primitives: ['embed', 'search', 'askCheap', 'askSmart'], code: 'const sanitized = redactSecrets(boundLogWindow(incident));\nconst hits = await search(await embed(incident.summary), {\n  index: runbookIndex, limit: 5,\n  filter: { service: incident.service }\n});\nconst context = { logs: sanitized, runbooks: hits.map(hit => hit.item) };\nconst timeline = await askCheap(\n  "Draft a timeline. Cite event IDs. Do not claim a root cause.",\n  { context }\n);\nconst hypotheses = await askSmart(\n  "Suggest checks for competing hypotheses. Cite the evidence.",\n  { context: { ...context, timeline } }\n);\n\nshowEvidenceBesideDrafts({ context, timeline, hypotheses });', takeaway: 'Generated text is a navigation aid over real evidence—not the incident verdict.', tradeoff: 'Redact secrets and customer data before model calls. Validate citations and distinguish correlation from cause.', measure: 'Evidence coverage, unsupported claims, and investigation time.' },
    { title: 'A read-only investigation loop', summary: 'Let reasoning choose a query while your executor enforces the boundaries.', primitives: ['askSmart', 'call'], code: 'const evidence = [];\n\nfor (let step = 0; step < 5; step++) {\n  const plan = await askSmart(\n    "Suggest a read-only check, or finish. Do not change production.",\n    { context: { incident, evidence },\n      tools: incidentToolDefinitions, schema: nextStepSchema }\n  );\n  if (plan.done) break;\n\n  const tool = requireReadOnlyTool(plan.tool, engineer);\n  const args = constrainToIncident(tool, plan.args, incident);\n  const result = await call(tool, args);\n  evidence.push(redactSecrets(result));\n}\n\nshowInvestigationTrace(evidence);', takeaway: 'The engineer owns the conclusion and any action. The model gets bounded instruments, not production authority.', tradeoff: 'Enforce authorization, time windows, result caps, and secret redaction outside the prompt.', measure: 'Useful evidence per query, investigation latency, and boundary violations.' },
  ] },
]

export const primitiveAliases: Record<string, PrimitiveId> = {
  llm: 'askSmart', classifier: 'classify', extraction: 'extract', embeddings: 'embed',
  retrieval: 'search', reranking: 'rerank', rag: 'search', tools: 'call', multimodal: 'inspect', evaluation: 'evaluate',
}
export const primitiveById = (id: string) => primitives.find(primitive => primitive.id === id)
export const problemBySlug = (slug: string) => problems.find(problem => problem.slug === slug)
