export type PrimitiveId = 'askCheapLLM' | 'askSmartLLM' | 'askDecisionModel' | 'embed' | 'similaritySearch'
export type Difficulty = 'Simple' | 'Medium' | 'Hard'

export interface Approach { title: string; summary: string; body: string; primitives: PrimitiveId[] }
export interface Problem { slug: string; title: string; question: string; description: string; category: string; difficulty: Difficulty; think: string[]; approaches: Approach[] }
export type ProblemSummary = Pick<Problem, 'slug' | 'title' | 'category' | 'difficulty'>
export interface Primitive {
  id: PrimitiveId; name: string; capability: string; short: string; color: string; tint: string
  input: string; output: string; mentalModel: string; underneath: string
  useful: string[]; notUseful: string[]; caution: string; providers: string[]; exampleCode: string
}

export const primitives: Primitive[] = [
  {
    id: 'askCheapLLM', name: 'askCheapLLM(prompt)', capability: 'Simple language tasks', color: '#367047', tint: '#e6f0e7',
    short: 'Summarize, rewrite, or extract text with a smaller language model.', input: 'A prompt with source text', output: 'Generated text',
    mentalModel: 'A large language model (LLM) generates text from a prompt: your instructions plus the source material. Treat it as a text-in, text-out building block. Give it one clear job and the facts it needs. “Cheap” describes a relative cost tier, not a promise about quality or price.',
    underneath: 'Your real implementation sends the prompt to a smaller language model through a provider API, then reads the response. Authentication, network calls, retries, and response limits are deliberately left out of the teaching code.',
    useful: ['Summarizing one document chunk', 'Rewriting text or drafting a short acknowledgment', 'High-volume, bounded tasks you can test on representative inputs'],
    notUseful: ['Hard, multi-step reasoning', 'Exact arithmetic your code can do', 'Treating generated text as verified facts'],
    caution: 'Your code supplies context, checks results, and handles failures. Test the smaller model first: retries and mistakes can erase the cost savings.',
    providers: ['OpenAI · GPT-4.1 mini', 'Anthropic · Claude Haiku family'],
    exampleCode: '// Put the task and source text in one prompt\nconst prompt = "Summarize this ticket in one sentence: " + ticket.text\n\n// Use a smaller LLM for this simple task\nconst summary = askCheapLLM(prompt)\n\n// Your application decides what happens next\nsave(summary)',
  },
  {
    id: 'askSmartLLM', name: 'askSmartLLM(prompt)', capability: 'Harder reasoning', color: '#79539d', tint: '#eee6f6',
    short: 'Connect evidence and work through ambiguity with a stronger language model.', input: 'A question and relevant evidence', output: 'An answer or explanation',
    mentalModel: 'Spend more reasoning where it matters. A stronger model can connect evidence and consider ambiguous cases, but it is still not an oracle.',
    underneath: 'Your implementation sends a prompt to a more capable model, often with more context or reasoning budget. It usually costs more or takes longer than a smaller model. The response is still generated text.',
    useful: ['Combining summaries into a coherent whole', 'Explaining unfamiliar code from supplied source', 'Investigating competing hypotheses using bounded evidence'],
    notUseful: ['Every item in a simple high-volume pipeline', 'Replacing a database query or exact calculation', 'Giving a model permission to change production'],
    caution: 'Keep sources next to answers. Your software and reviewers own validation, permissions, and real-world actions. Stronger models can still invent convincing explanations.',
    providers: ['OpenAI · GPT-4.1 / reasoning-capable models', 'Anthropic · Claude Sonnet / Opus families'],
    exampleCode: '// Give the model evidence, not just a question\nconst prompt = "Compare these incident hypotheses using the evidence: " + evidence\n\n// Spend more reasoning on an ambiguous problem\nconst explanation = askSmartLLM(prompt)\n\n// An engineer checks the explanation against the sources\nshowWithSources(explanation, evidence)',
  },
  {
    id: 'askDecisionModel', name: 'askDecisionModel(input, prompt, options?)', capability: 'Structured decisions', color: '#326a9e', tint: '#e5eef8',
    short: 'Ask an LLM for a choice, a yes/no decision, or a numeric score.', input: 'Input + decision question + optional choices', output: 'Choice · Boolean (yes/no) · Score',
    mentalModel: 'A fuzzy switch statement, boolean check, or rating. Choice picks one option. Boolean returns true or false for a yes/no question. Score returns a number against an explicit rubric. These are three output modes of one primitive, not three new functions.',
    underneath: 'Your implementation prompts an LLM with the input and a constrained output format, then validates and parses the result. An options list requests a Choice; without a list, the prompt specifies Boolean or Score. The same small or strong LLM providers can power this building block.',
    useful: ['Choice: route a ticket to a known queue', 'Boolean: decide whether feedback describes a bug', 'Score: rate urgency using a clearly defined scale'],
    notUseful: ['Deterministic rules from structured data', 'Open-ended prose that belongs in an LLM prompt', 'A calibrated probability or automatic approval of a high-stakes action'],
    caution: 'Validate choices, booleans, and score ranges in real code. A rating is not confidence or probability. Include an “other” option where useful; test decisions against human-labeled examples.',
    providers: ['OpenAI · models with structured outputs', 'Anthropic · Claude with constrained output and validation'],
    exampleCode: '// Choice: pick one of the supplied options\nconst category = askDecisionModel(\n  ticket.text,\n  "What type of ticket is this?",\n  ["billing", "technical", "account", "other"]\n)\n\n// Boolean: ask for a yes/no decision\nconst needsReview = askDecisionModel(\n  ticket.text, "Does this mention a legal threat? Return yes/no."\n)\n\n// Score: define the scale, not an imagined probability\nconst urgency = askDecisionModel(\n  ticket.text, "Rate urgency from 1 (routine) to 5 (service blocked)."\n)\n\n// Ordinary code owns the routing\nif (needsReview || category === "other") {\n  queueForReview(ticket)\n} else {\n  route(ticket, category, urgency)\n}',
  },
  {
    id: 'embed', name: 'embed(text)', capability: 'Meaning as a vector', color: '#8c511e', tint: '#f6eadb',
    short: 'Turn text into a list of numbers that captures its meaning.', input: 'Text', output: '[0.12, -0.81, 0.34, …]',
    mentalModel: 'A coordinate for meaning. Related text tends to land nearby in vector space. It does not search, answer questions, or prove two records are identical. Your ordinary code uses the vector for search, grouping, or matching.',
    underneath: 'An embedding model encodes the text into a list of numbers. Your software stores these vectors and compares them using a similarity metric or vector index. Use the same model for indexed content and queries.',
    useful: ['Searching documents by meaning rather than exact words', 'Finding related feedback or code', 'Finding candidate transaction matches before exact checks'],
    notUseful: ['Exact IDs, amounts, or currencies', 'Generating summaries or answers', 'Proving identity from semantic similarity alone'],
    caution: 'Similarity is not correctness. Keep access filters and exact constraints in code. Changing embedding models generally requires rebuilding your index.',
    providers: ['OpenAI · text-embedding-3-small / large', 'Cohere · Embed family'],
    exampleCode: '// Split document text into small sections with ordinary code\nconst chunks = splitIntoSections(document)\nfor (const chunk of chunks) {\n  const vector = embed(chunk.text)\n  // Store the text and vector together in your database\n  saveChunk(chunk, vector)\n}\n\n// Encode the question using the same embedding model\nconst questionVector = embed(question)\n// Read saved text and vectors; only include documents this user can see\nconst savedChunks = loadDocumentChunks(user)\n// Compare vectors and return the chunks closest to the question\nconst relevantChunks = similaritySearch(questionVector, savedChunks)\n// Display the original text and document names\nshowSources(relevantChunks)',
  },
  {
    id: 'similaritySearch', name: 'similaritySearch(query, indexedItems, limit?)', capability: 'Search by meaning', color: '#28766f', tint: '#e4f1ec',
    short: 'Find related items even when they use completely different words.', input: 'A question or vector + searchable items', output: 'A ranked list of matching items',
    mentalModel: 'A meaning-aware lookup. “I cannot sign in” can find a guide titled “Reset your login credentials.” It returns existing passages or records, not a generated answer. If you already have a vector from embed(), pass that instead of the question.',
    underneath: 'Prepare your collection once: split long documents into passages, call embed() on each passage, and save the text, vector, source, and access permissions together. At query time this block embeds a text question with the same model, or uses the vector you supply. Ordinary search code compares those vectors and returns the closest permitted items. No language model writes an answer. A vector is just a list of numbers; nearby vectors tend to represent related meanings.',
    useful: ['Finding a policy when the user does not know its exact wording', 'Retrieving evidence before asking a model to answer', 'Finding similar tickets, records, or runbooks for human review'],
    notUseful: ['Exact invoice IDs, bank amounts, or error codes', 'Proving identity or guaranteeing an answer is true', 'Bypassing access checks or replacing an authoritative database lookup'],
    caution: 'Only search items the current user is allowed to access. Indexed content and questions must use the same embedding model. The optional limit caps results (five by default in this teaching abstraction). Your implementation defines a minimum relevance threshold, tuned on real examples; return an empty list if nothing meets it. Even returned items can be irrelevant. Similarity scores are not probabilities.',
    providers: ['PostgreSQL + pgvector', 'An embedding provider + a vector index', 'An in-memory vector comparison for small collections'],
    exampleCode: '// SETUP: index each passage once, not for every question.\nfor (const passage of documentPassages) {\n  // A vector is a list of numbers representing meaning.\n  const vector = embed(passage.text)\n  // Keep the original text, source, and permissions too.\n  saveChunk(passage, vector)\n}\n\n// LOOKUP: search only items this user is allowed to read.\nconst passages = loadDocumentChunks(user)\n\n// “Cannot sign in” can match “Reset login credentials”.\n// The block embeds the question and compares saved vectors.\n// Return up to 5 useful matches, or [] if none qualify.\nconst sources = similaritySearch(question, passages, 5)\n\nif (sources.length === 0) {\n  showNoEvidence()\n} else {\n  // These are real passages, not an invented answer.\n  showSources(sources)\n}',
  },
]

export const problems: Problem[] = [
  {
    slug: 'classify-support-tickets', title: 'Classify support tickets', question: 'How would you route 100K support tickets?',
    description: '“I was charged twice.” “I can’t log in.” “Your API is down.” Send messages to billing, account, or technical support without spending a big-model budget on every ticket.', category: 'Operations', difficulty: 'Simple',
    think: ['What routing information do you already have?', 'What should happen to a message that fits no category?', 'Which mistakes need human review?'],
    approaches: [
      { title: 'Use the signal you already have', summary: 'Structured form fields and ordinary rules.', primitives: [], body: 'A selected topic may already solve the problem. Start here before adding a model.\n\n```ts\n// A structured field needs no AI\nconst queues = ["billing", "technical", "account"]\n\nfor (const ticket of tickets) {\n  if (queues.includes(ticket.selectedTopic)) {\n    route(ticket, ticket.selectedTopic)\n  } else {\n    queueForReview(ticket)\n  }\n}\n```\n\n**Trade-off:** predictable and inexpensive, but free-text messages stay unresolved. Measure incorrect routing and review volume.' },
      { title: 'Let a model make the choice', summary: 'AI interprets the text. Your application routes it.', primitives: ['askDecisionModel'], body: 'Use a **Choice** decision when categories are known. “Other” is a deliberate escape hatch.\n\n```ts\nfor (const ticket of tickets) {\n  // Ask for a category, not a long explanation\n  const category = askDecisionModel(\n    ticket.text,\n    "What type of ticket is this?",\n    ["billing", "technical", "account", "other"]\n  )\n\n  // Keep the action in ordinary code\n  if (category === "other") {\n    queueForReview(ticket)\n  } else {\n    route(ticket, category)\n  }\n}\n```\n\n**Trade-off:** handles different wording, but model decisions can be wrong. Validate allowed labels and test precision per queue before enabling automatic routing.' },
      { title: 'Use resolved tickets as precedents', summary: 'Find similar cases and let a human verify the route.', primitives: ['embed', 'similaritySearch', 'askCheapLLM'], body: 'If your queue definitions change often, verified resolved tickets can be useful evidence. Here, an **agent means a human support agent**, not an autonomous AI. `similaritySearch()` finds earlier tickets with related meanings; a small model summarizes them for the person.\n\n```ts\n// SETUP: resolved ticket descriptions were embedded and saved earlier.\n// Only search verified cases this human agent can access.\nconst tickets = loadResolvedTickets(agent)\n// Encode the new message using that same embedding model.\nconst vector = embed(ticket.text)\n// Compare stored vectors and return tickets with the closest meanings\nconst similarTickets = similaritySearch(vector, tickets)\n\n// A simple summary helps the agent scan precedents\nconst prompt = "Summarize how these cases were routed: " + similarTickets\nconst summary = askCheapLLM(prompt)\nshowToAgent(ticket, similarTickets, summary)\n```\n\nSimilarity finds a precedent, not a guaranteed route. **Trade-off:** adaptable, but stale examples mislead. Measure useful precedent recall and agent corrections.' },
    ],
  },
  {
    slug: 'summarize-documents', title: 'Summarize documents', question: 'How would you summarize a huge document?',
    description: 'Turn a 300-page report into a useful summary without losing important caveats or stuffing the whole document into every model call.', category: 'Documents', difficulty: 'Simple',
    think: ['Does the document fit in one model input?', 'What gets lost when each section is summarized separately?', 'How will the reader verify important claims?'],
    approaches: [
      { title: 'One focused prompt', summary: 'A small model and a short document.', primitives: ['askCheapLLM'], body: 'For a short report, splitting and orchestration may add nothing.\n\n```ts\n// Include the source and a clear summary task\nconst prompt = "Summarize the key findings and caveats: " + document\nconst summary = askCheapLLM(prompt)\n\n// Keep the original available for verification\nshowWithSources(summary, document)\n```\n\n**Trade-off:** simple, but only suitable when the source fits and the task is bounded. Measure coverage and unsupported claims.' },
      { title: 'Summarize chunks, then synthesize', summary: 'Cheap calls for the parts. Stronger reasoning for the whole.', primitives: ['askCheapLLM', 'askSmartLLM'], body: 'This is a normal loop with two different AI building blocks.\n\n```ts\n// Split at section boundaries using ordinary code\nconst documentChunks = splitIntoSections(document)\nconst summaries = []\n\nfor (const chunk of documentChunks) {\n  // Use a smaller model for each narrow task\n  const prompt = "Summarize this section. Keep caveats: " + chunk\n  const summary = askCheapLLM(prompt)\n  summaries.push(summary)\n}\n\n// Synthesize the parts with a stronger model\nconst finalPrompt = "Combine these summaries. Note conflicts: " + summaries\nconst finalSummary = askSmartLLM(finalPrompt)\nshowWithSources(finalSummary, documentChunks)\n```\n\n> Summaries are lossy. Preserve section references and verify critical claims against the original. If the collected summaries are still too large, repeat the grouping step.\n\n**Trade-off:** scales to larger inputs, but errors or omissions can propagate. Test key-finding coverage and citation accuracy.' },
      { title: 'Summarize only what the reader needs', summary: 'Retrieve relevant sections before writing a focused summary.', primitives: ['embed', 'similaritySearch', 'askSmartLLM'], body: 'A user asking about financial risk may not need a summary of every chapter. Assume sections were already embedded into an authorized index.\n\n```ts\n// Find relevant evidence for this specific question\nconst vector = embed(readerQuestion)\n// Read document sections and their saved vectors; check user access\nconst sections = loadDocumentSections(user)\n// Compare vectors and return the most relevant sections\nconst relevantSections = similaritySearch(vector, sections)\n\nconst prompt = "Summarize these sections for the question. Cite sources: "\n  + readerQuestion + relevantSections\nconst summary = askSmartLLM(prompt)\n// Display the summary beside the original sections\nshowWithSources(summary, relevantSections)\n```\n\n**Trade-off:** focused and cheaper than processing everything, but retrieval can miss important context. This is not a complete-document summary.' },
    ],
  },
  {
    slug: 'analyze-customer-feedback', title: 'Analyze customer feedback', question: 'How would you make sense of 20K customer comments?',
    description: 'Identify recurring themes and urgent complaints while keeping the original feedback visible. Avoid turning a model’s interpretation into invented product statistics.', category: 'Product', difficulty: 'Simple',
    think: ['Are the themes already known, or do you need to discover them?', 'Which counts should be computed in code?', 'How will you preserve minority but high-impact complaints?'],
    approaches: [
      { title: 'Count known themes', summary: 'Structured choices plus deterministic aggregation.', primitives: ['askDecisionModel'], body: 'Use stable categories when the team already knows what it wants to track.\n\n```ts\nfor (const comment of feedback) {\n  // Choice identifies a theme\n  const theme = askDecisionModel(\n    comment.text, "Pick the main feedback theme.",\n    ["pricing", "performance", "usability", "other"]\n  )\n  incrementCount(theme)\n  saveExample(theme, comment)\n}\n\n// Counts come from your code, not generated prose\nshowThemeCounts()\n```\n\n**Trade-off:** easy to track over time, but a single label can hide multi-theme feedback. Measure label accuracy and inspect “other” examples.' },
      { title: 'Discover themes from similar comments', summary: 'Embeddings for grouping, text generation for labels.', primitives: ['embed', 'askCheapLLM'], body: 'You do not need to know the themes in advance. An **embedding** is a list of numbers representing a comment’s meaning. **Clustering** means putting nearby lists into groups: comments about slow loading may end up together even if they use different words. A small model then gives each group a readable label.\n\n```ts\n// Keep each original comment beside its meaning vector.\nconst vectors = []\nfor (const comment of feedback) {\n  const vector = embed(comment.text)\n  vectors.push({ comment, vector })\n}\n\n// Group nearby vectors with ordinary clustering code\nconst groups = clusterVectors(vectors)\nfor (const group of groups) {\n  // Pick a small sample so the prompt stays manageable.\n  const examples = representativeComments(group)\n  // AI names the group; it does not invent its size or members.\n  const label = askCheapLLM("Name the shared theme: " + examples)\n  // Display the actual comments so people can verify the grouping.\n  showGroup(label, group.comments)\n}\n```\n\n**Trade-off:** discovers unexpected themes, but grouping and labels can change across runs. Keep outliers and validate group coherence with people.' },
      { title: 'Separate urgency from popularity', summary: 'A score prioritizes review without pretending to be a probability.', primitives: ['askDecisionModel'], body: 'A rare complaint about lost data may matter more than hundreds of requests for a new color.\n\n```ts\nfor (const comment of feedback) {\n  // Score against an explicit, repeatable rubric\n  const impact = askDecisionModel(\n    comment.text,\n    "Rate impact 1–5: 1 cosmetic, 3 blocked task, 5 lost data."\n  )\n  if (impact >= 4) {\n    queueForReview(comment)\n  }\n}\n```\n\n**Trade-off:** adds a judgment call. Calibrate the rubric on reviewed examples, and do not interpret a 5 as certainty.' },
    ],
  },
  {
    slug: 'search-documents', title: 'Search internal documents', question: 'How would you find an answer inside your internal docs?',
    description: 'Find the right policy or runbook even when the question uses different wording. Every result must respect the user’s access, and answers should show their evidence.', category: 'Knowledge', difficulty: 'Medium',
    think: ['Will an exact keyword search already work?', 'When do you create and store embeddings?', 'What happens if the evidence is missing or contradictory?'],
    approaches: [
      { title: 'Search exact words', summary: 'An ordinary search index may be enough.', primitives: [], body: 'Precise product names and error codes often want exact lookup.\n\n```ts\n// Read documents from the database, limited to what this user can see\nconst documents = loadDocuments(user)\n// Look for the words in the question using a normal text search\nconst results = findText(question, documents)\n// Show the matching passages and their document names\nshowSources(results)\n```\n\n**Trade-off:** fast and transparent, but misses paraphrases. Measure useful results for real user questions.' },
      { title: 'Search by meaning', summary: 'Embed the source once, then embed each question.', primitives: ['embed', 'similaritySearch'], body: '“Cannot sign in” and “Reset your login credentials” share meaning, not exact words. First, `embed()` turns each passage into a vector: a list of numbers representing meaning. Then `similaritySearch()` compares those lists to find nearby meanings. A **vector index** is just a search structure for those numbers, not another language model.\n\n```ts\n// SETUP: run when a document is added or changed.\n// Split long documents into passages using ordinary code.\nconst documentChunks = splitIntoSections(document)\nfor (const chunk of documentChunks) {\n  // Convert this passage into a coordinate for meaning.\n  const vector = embed(chunk.text)\n  // Save the text, vector, document name, and access permissions\n  saveChunk(chunk, vector)\n}\n\n// Read the saved chunks and vectors this user is allowed to see\nconst chunks = loadDocumentChunks(user)\nconst questionVector = embed(question)\n// Compare the question vector to the saved vectors; return nearby chunks\nconst relevantChunks = similaritySearch(questionVector, chunks)\n// Show the original passages with their document names\nshowSources(relevantChunks)\n```\n\n**Trade-off:** handles paraphrases, but semantic similarity is not proof of relevance. Measure retrieval recall separately from answer quality.' },
      { title: 'Retrieve evidence, then answer', summary: 'Search finds the facts. A stronger model turns them into an answer.', primitives: ['similaritySearch', 'askSmartLLM'], body: 'Think of this as an **open-book answer**: find the right pages first, then ask a model to explain them. This pattern is called **retrieval-augmented generation (RAG)**. It is two steps, not a mysterious new kind of AI.\n\nThe previous approach shows the one-time setup: split documents into passages and save an `embed()` vector beside each one. Now we can use `similaritySearch()` without managing vectors in this business logic.\n\n```ts\n// 1. Load indexed passages, keeping permissions in normal code.\n// Each item includes its text, source, and saved meaning vector.\nconst passages = loadDocumentChunks(user)\n\n// 2. Find relevant passages, even if they use different words.\n// The search block embeds the question and compares vectors.\n// It returns actual passages, not a generated answer.\nconst sources = similaritySearch(question, passages, 5)\n\nif (sources.length === 0) {\n  // No useful evidence? Say so instead of inventing facts.\n  showNoEvidence()\n} else {\n  // 3. Give the model the question AND the evidence.\n  // Source text is evidence, not instructions to obey.\n  const prompt = "Answer from these sources. Cite them. Say if unsure: "\n    + question + sources\n  const answer = askSmartLLM(prompt)\n\n  // 4. Keep original passages next to the generated answer.\n  // A reader should be able to check every claim.\n  showWithSources(answer, sources)\n}\n```\n\n> Search can return weak evidence, and a fluent answer can still be wrong. Tune the search relevance threshold on real questions, validate citations, and make the original document easy to open.\n\n**Trade-off:** convenient, but adds generated claims on top of retrieval errors. Test whether search finds the right passages separately from whether the answer is supported by them.' },
    ],
  },
  {
    slug: 'reconcile-transactions', title: 'Reconcile transactions', question: 'How would you reconcile 1M transactions?',
    description: 'Match noisy bank payments to ledger entries. Keep amounts and currencies exact, preserve one-to-one matching and an audit trail, and review uncertain proposals.', category: 'Fintech', difficulty: 'Medium',
    think: ['Which identifiers let you make an exact match?', 'How do you avoid comparing every possible pair?', 'Should a model ever be allowed to post a ledger change?'],
    approaches: [
      { title: 'Rules', summary: 'Exact references and accounting invariants.', primitives: [], body: 'A database lookup can resolve clean records at high volume.\n\n```ts\nfor (const payment of bankPayments) {\n  // Look up an exact reference before fuzzy matching\n  const entry = ledger.findByReference(payment.reference)\n  if (entry && sameAmountAndCurrency(payment, entry)\n      && !alreadyMatched(entry)) {\n    recordExactMatch(payment, entry)\n  } else {\n    queueForReview(payment)\n  }\n}\n```\n\n**Trade-off:** explainable and inexpensive, but missing or inconsistent references remain unresolved. Measure exact-match precision and unmatched volume.' },
      { title: 'Rules + askDecisionModel()', summary: 'Let a structured decision assess a small candidate set.', primitives: ['askDecisionModel'], body: 'Hard constraints narrow the search. AI interprets descriptions only after that.\n\n```ts\n// Exact amount, currency, date window, account, and unmatched status\nconst candidates = loadLedgerEntries(payment)\nfor (const entry of candidates) {\n  const pair = { payment, entry }\n  // Boolean: a yes/no judgment, not an accounting authorization\n  const likelyMatch = askDecisionModel(\n    pair, "Do these descriptions refer to the same payment? Return yes/no."\n  )\n  if (likelyMatch) {\n    proposeMatchForReview(payment, entry)\n  }\n}\n```\n\n**Trade-off:** useful for ambiguity, but one call per candidate can be expensive. Human review and deterministic one-to-one checks own the final match.' },
      { title: 'Search for plausible matches', summary: 'Use similaritySearch() to narrow a million records to a few candidates.', primitives: ['embed', 'similaritySearch'], body: '“ACME subscription” and “ACME monthly plan” may describe the same payment. During setup, embed ledger descriptions and store those meaning vectors with the entries. `similaritySearch()` returns nearby meanings as candidates, not approved matches. Exact amount, currency, and account checks still belong in code.\n\n```ts\nconst vector = embed(payment.description)\n// Read unmatched entries with the same account, amount, and currency\nconst entries = loadLedgerEntries(payment)\n// Compare description vectors and return the closest matching entries\nconst candidates = similaritySearch(vector, entries)\n\nfor (const entry of candidates) {\n  if (withinDateWindow(payment, entry)) {\n    proposeMatchForReview(payment, entry)\n  }\n}\n```\n\n**Trade-off:** scalable candidate discovery, not proof of a match. Measure whether the correct entry makes it into the candidate list.' },
      { title: 'A hybrid pipeline', summary: 'Exact rules first, semantic candidates second, model judgment last.', primitives: ['embed', 'similaritySearch', 'askDecisionModel'], body: 'Each stage does less work than the previous one. None gets permission to bypass ledger invariants.\n\n```ts\n// Match by reference; check account, amount, currency, and unmatched status\nconst exactMatch = findExactMatch(payment)\nif (exactMatch) {\n  recordExactMatch(payment, exactMatch)\n} else {\n  const vector = embed(payment.description)\n  // Read unmatched entries with the same account, amount, currency, and date window\n  const entries = loadLedgerEntries(payment)\n  // Compare saved description vectors to find a small set of candidates\n  const candidates = similaritySearch(vector, entries)\n\n  for (const entry of candidates) {\n    const pair = { payment, entry }\n    const score = askDecisionModel(\n      pair, "Rate description agreement from 1 (unrelated) to 5 (strong match)."\n    )\n    saveReviewCandidate(payment, entry, score)\n  }\n  // Reviewers approve; code enforces one-to-one matching and audit records\n  openReviewQueue(payment)\n}\n```\n\n| Stage | What it owns |\n| --- | --- |\n| Rules | Exact accounting constraints |\n| Embeddings | Candidate discovery |\n| Decision model | Review prioritization |\n| Human + software | Approval, one-to-one matching, audit trail |\n\n**Trade-off:** more moving parts, but the expensive judgment is bounded. Measure total cost, candidate recall, and reviewer corrections—not just the number of automatic matches.' },
    ],
  },
  {
    slug: 'understand-codebase', title: 'Understand a codebase', question: 'How would you locate and explain unfamiliar code?',
    description: 'Find “the code that retries failed jobs” even when the repository uses different names. Ground explanations in source paths, and keep repository permissions intact.', category: 'Developer Tools', difficulty: 'Medium',
    think: ['Does the user know a symbol or only a behavior?', 'What context does a useful explanation need?', 'How can the user check an answer against the actual code?'],
    approaches: [
      { title: 'Follow symbols and references', summary: 'Existing developer tools, no generated explanation.', primitives: [], body: 'Exact names want exact tools.\n\n```ts\n// Read source files from a repository this user can access\nconst files = loadFiles(user)\n// Find function or class names that match the query\nconst symbols = findSymbols(query, files)\nfor (const symbol of symbols) {\n  // Find the places where this function or class is used\n  const references = findReferences(symbol, files)\n  // Display the definition and its callers\n  showCode(symbol, references)\n}\n```\n\n**Trade-off:** precise and cheap, but a behavior description may not match any symbol.' },
      { title: 'Combine keywords and meaning', summary: 'Ordinary search plus embedding-based retrieval.', primitives: ['embed', 'similaritySearch'], body: 'Assume symbol-sized chunks were embedded with their paths. Preserve the exact search rather than replacing it.\n\n```ts\n// Read code snippets and saved vectors from a repository the user can access\nconst snippets = loadCodeSnippets(user)\n// Ordinary text search finds exact words and function names\nconst exact = findText(query, snippets)\nconst vector = embed(query)\n// Compare vectors to find code with a similar meaning\nconst semantic = similaritySearch(vector, snippets)\n\n// Combine both lists and remove repeated snippets\nconst results = removeDuplicates(exact, semantic)\n// Display each snippet with its file path\nshowCode(results)\n```\n\n**Trade-off:** better for descriptions, but stale indexes can point to deleted code. Measure top-result relevance and keep indexing tied to revisions.' },
      { title: 'Explain retrieved code', summary: 'Reason over real source, not an imagined repository.', primitives: ['embed', 'similaritySearch', 'askSmartLLM'], body: 'The answer is a second step after finding evidence.\n\n```ts\nconst vector = embed(question)\n// Read saved code snippets and vectors; check repository access\nconst snippets = loadCodeSnippets(user)\n// Compare vectors and return the most relevant code snippets\nconst sources = similaritySearch(vector, snippets)\n\nif (sources.length === 0) {\n  showNoEvidence()\n} else {\n  const prompt = "Explain this code for the question. Cite file paths: "\n    + question + sources\n  const explanation = askSmartLLM(prompt)\n  showWithSources(explanation, sources)\n}\n```\n\n**Trade-off:** convenient, but a snippet may omit callers or runtime behavior. Verify claims and follow references in normal code tools.' },
    ],
  },
  {
    slug: 'automate-workflow', title: 'Automate a multi-step workflow', question: 'How would you automate a workflow without handing over control?',
    description: 'Help an operations team gather evidence and prepare an onboarding checklist. Models may suggest steps; software owns permissions, budgets, and approval of external actions.', category: 'Operations', difficulty: 'Hard',
    think: ['Is the workflow fixed or does it need branching?', 'Which steps are safe to run automatically?', 'What stops the loop from running forever?'],
    approaches: [
      { title: 'A fixed workflow with one AI step', summary: 'Use a model for writing, not orchestration.', primitives: ['askCheapLLM'], body: 'If the sequence is known, an agent loop is unnecessary.\n\n```ts\n// Gather facts through permission-checked ordinary APIs\nconst account = loadAccount(user, accountId)\n// Build the required onboarding steps from account fields\nconst checklist = buildChecklist(account)\nconst prompt = "Draft an onboarding note from these facts: " + checklist\nconst draft = askCheapLLM(prompt)\n\n// Sending the note is a separate approval step\nshowDraftForApproval(draft, checklist)\n```\n\n**Trade-off:** predictable and easy to test, but does not handle unexpected branching.' },
      { title: 'Model decisions inside a state machine', summary: 'AI selects a branch; code defines every possible action.', primitives: ['askDecisionModel'], body: 'A constrained Choice can handle ambiguous input without creating an open-ended executor.\n\n```ts\nconst nextStep = askDecisionModel(\n  request, "What information is missing for onboarding?",\n  ["account details", "access policy", "ready for review"]\n)\n\n// Only registered read-only branches are possible\nif (nextStep === "account details") {\n  showAccountDetails(user, accountId)\n} else if (nextStep === "access policy") {\n  // Display the access policy this user is allowed to read\n  showPolicy(user)\n} else {\n  openApprovalChecklist(request)\n}\n```\n\n**Trade-off:** bounded and auditable, but the branching logic must be maintained as requirements evolve.' },
      { title: 'A bounded planning loop', summary: 'A stronger model reasons; a decision model picks an allowed step.', primitives: ['askSmartLLM', 'askDecisionModel'], body: 'An agent-like workflow is a loop around normal application code. Keep it read-only until a person approves the proposed changes.\n\n```ts\n// Keep a record of facts gathered so far.\nconst evidence = []\n// The loop can run at most four times, even if AI keeps asking.\nfor (let step = 0; step < 4; step++) {\n  // Reason about missing facts, not actions to execute directly.\n  const prompt = "What onboarding evidence is still missing? "\n    + request + evidence\n  const reasoning = askSmartLLM(prompt)\n  // Translate the reasoning into one of our allowed choices.\n  const action = askDecisionModel(\n    reasoning, "Choose the next permitted read-only step.",\n    ["read account", "read policy", "finish"]\n  )\n\n  if (action === "finish") break\n  // Read account or policy data based on the choice; enforce access and limits\n  const result = runReadOnlyStep(action, user)\n  evidence.push(result)\n}\n\nshowChecklistForApproval(request, evidence)\n```\n\n> The prompt is not a permission boundary. Enforce allowlists, access checks, timeouts, and a step budget in the executor.\n\n**Trade-off:** flexible, but slower and harder to test. Measure useful evidence per step, completion, and boundary violations.' },
    ],
  },
  {
    slug: 'detect-suspicious-transactions', title: 'Detect suspicious transactions', question: 'How would you triage suspicious transactions?',
    description: 'Prioritize transactions for an analyst without mistaking a language-model score for a fraud probability. Preserve evidence and keep adverse actions under established controls.', category: 'Fintech', difficulty: 'Hard',
    think: ['Which signals are numerical and already covered by rules?', 'What can a model infer from description text alone?', 'How will you measure missed cases and false alarms?'],
    approaches: [
      { title: 'Rules and existing risk signals', summary: 'Deterministic triage from trusted data.', primitives: [], body: 'Start with your existing risk system and auditable rules.\n\n```ts\nfor (const transaction of transactions) {\n  // Read verified signals from your existing risk system\n  const signals = loadRiskSignals(transaction)\n  if (signals.velocityExceeded || signals.knownBlockedRecipient) {\n    queueForAnalyst(transaction, signals)\n  }\n}\n```\n\n**Trade-off:** transparent, but can miss novel patterns. Measure alert precision and missed confirmed cases.' },
      { title: 'Use text judgment as one additional signal', summary: 'A rubric score helps review; it never freezes an account.', primitives: ['askDecisionModel'], body: 'Only send minimized, authorized data to the model. Do not use prose analysis as a replacement for a validated fraud model.\n\n```ts\n// Keep relevant facts, removing personal identifiers and secrets\nconst context = removePrivateData(transaction)\nconst concern = askDecisionModel(\n  context,\n  "Rate description inconsistency 1–5. Missing context is not fraud."\n)\n\n// This is a review priority, not a fraud probability\nsaveAnalystSignal(transaction.id, concern)\nqueueForAnalyst(transaction, context)\n```\n\n**Trade-off:** adds a subjective signal and potential bias. Test on labeled cases across customer segments and keep adverse actions outside this path.' },
      { title: 'Find patterns, then assemble evidence', summary: 'Similarity finds related cases; reasoning helps the analyst inspect them.', primitives: ['embed', 'similaritySearch', 'askSmartLLM'], body: 'Assume reviewed, permission-scoped cases are already indexed. A similar case is not an accusation.\n\n```ts\n// Keep only relevant description fields; remove personal data and secrets\nconst description = removePrivateData(transaction.description)\nconst vector = embed(description)\n// Read reviewed cases and saved vectors this analyst can access\nconst reviewedCases = loadReviewedCases(analyst)\n// Compare vectors to find cases with similar descriptions\nconst cases = similaritySearch(vector, reviewedCases)\n\nconst prompt = "Compare these cases. Separate facts from hypotheses: "\n  + description + cases\nconst note = askSmartLLM(prompt)\nshowAnalystEvidence(transaction, cases, note)\n```\n\n**Trade-off:** helps discover patterns, but similar wording can be harmless. Audit unsupported claims and analyst corrections; require independent evidence.' },
    ],
  },
  {
    slug: 'investigate-production-incidents', title: 'Investigate production incidents', question: 'How would you investigate an incident in noisy production logs?',
    description: 'Turn a noisy incident stream into evidence an engineer can inspect. Help form and test hypotheses without treating a generated explanation as the root cause.', category: 'Reliability', difficulty: 'Hard',
    think: ['Can traces, timestamps, and deploy history explain the incident?', 'What sensitive data must be removed before a model call?', 'Which hypotheses have actual supporting evidence?'],
    approaches: [
      { title: 'Start with observability', summary: 'Ordinary queries build a reliable timeline.', primitives: [], body: 'A model cannot repair missing trace IDs or timestamps.\n\n```ts\n// Group log entries with the same error message\nconst errors = groupByError(logs)\n// Look up request traces using the IDs recorded in each log\nconst traces = loadTraces(errors)\n// Read deployments made during the incident time window\nconst deploys = loadDeployments(incident.window)\n// Display the errors, requests, and deployments on one timeline\nshowTimeline(errors, traces, deploys)\n```\n\n**Trade-off:** best for known signals, but unfamiliar failures still need investigation. Track time to useful evidence.' },
      { title: 'Summarize evidence and retrieve runbooks', summary: 'Small summaries, semantic retrieval, stronger synthesis.', primitives: ['askCheapLLM', 'embed', 'similaritySearch', 'askSmartLLM'], body: 'Treat source text as untrusted data. Minimize and redact logs before sending them to a model.\n\n```ts\n// Read only logs from the incident time window\nconst incidentLogs = loadLogs(incident.window)\n// Remove secrets and personal data before sending anything to a model\nconst logs = removePrivateData(incidentLogs)\nconst timeline = askCheapLLM("Summarize events with their IDs: " + logs)\n\nconst vector = embed(incident.summary)\n// Read troubleshooting guides and saved vectors this engineer can access\nconst guides = loadRunbooks(engineer)\n// Compare vectors to find guides related to this incident\nconst runbooks = similaritySearch(vector, guides)\n\nconst prompt = "Suggest competing hypotheses and checks. Cite evidence: "\n  + timeline + runbooks\nconst hypotheses = askSmartLLM(prompt)\nshowWithSources(hypotheses, logs, runbooks)\n```\n\n**Trade-off:** reduces scanning time, but correlation is not causation. Validate citations and test each hypothesis using actual telemetry.' },
      { title: 'A read-only investigation loop', summary: 'Reasoning selects bounded checks; an engineer owns the conclusion.', primitives: ['askSmartLLM', 'askDecisionModel'], body: 'Give the model a small set of instruments, not production authority.\n\n```ts\nconst evidence = []\nfor (let step = 0; step < 5; step++) {\n  const prompt = "What incident hypothesis should we check next? "\n    + incident + evidence\n  const hypothesis = askSmartLLM(prompt)\n  const check = askDecisionModel(\n    hypothesis, "Pick a permitted check.",\n    ["read traces", "read deploys", "read metrics", "finish"]\n  )\n  if (check === "finish") break\n\n  // Read the selected traces, deployments, or metrics for this incident\n  // This helper enforces access, time windows, redaction, and result limits\n  const result = runReadOnlyCheck(check, engineer, incident)\n  evidence.push(result)\n}\nshowInvestigationTrace(evidence)\n```\n\n**Trade-off:** flexible exploration at extra cost and latency. Keep changes to production behind separate approval and existing runbooks.' },
    ],
  },
  {
    slug: 'extract-messy-invoices', title: 'Read messy invoices', question: 'How would you turn messy invoices into validated fields?',
    description: 'Convert text from PDFs or OCR into draft invoice data. Missing values must stay missing, and model output must never bypass arithmetic or business checks.', category: 'Documents', difficulty: 'Medium',
    think: ['Is the layout stable enough for a template?', 'What should missing or unreadable fields become?', 'Which values can you verify with deterministic code?'],
    approaches: [
      { title: 'Parse a known layout', summary: 'Templates and validators for predictable vendors.', primitives: [], body: 'PDF text extraction and OCR are ordinary infrastructure here, not additional teaching primitives.\n\n```ts\n// Read PDF text; for scans, use OCR to turn the image into text\nconst text = readInvoiceText(invoice)\nconst template = findVendorTemplate(text)\nif (template) {\n  const fields = parseWithTemplate(text, template)\n  if (validInvoice(fields)) {\n    saveDraft(fields)\n  } else {\n    queueForReview(invoice, fields)\n  }\n} else {\n  queueForReview(invoice)\n}\n```\n\n**Trade-off:** inexpensive for stable vendors, brittle when layouts change.' },
      { title: 'Ask a small LLM for draft fields', summary: 'A prompt requests JSON; normal code parses and validates it.', primitives: ['askCheapLLM'], body: 'You do not need a new extraction primitive. A language model responds to an explicit prompt.\n\n```ts\n// Read PDF text; for scans, use OCR to turn the image into text\nconst text = readInvoiceText(invoice)\nconst prompt = "Return JSON with vendor, total, currency. Use null if missing: "\n  + text\nconst response = askCheapLLM(prompt)\n\n// Parse JSON and validate field names and types; invalid data returns null\nconst fields = parseInvoiceJson(response)\nif (fields && matchesSource(fields, invoice)) {\n  saveDraft(fields)\n} else {\n  queueForReview(invoice, response)\n}\n```\n\n**Trade-off:** handles varying wording, but well-shaped data can still be wrong. Recalculate totals and verify high-value fields against the source.' },
      { title: 'Escalate failed drafts', summary: 'Use stronger reasoning only on the difficult inputs.', primitives: ['askCheapLLM', 'askSmartLLM'], body: 'A stronger model can help interpret messy text, but cannot recover facts from an unreadable scan.\n\n```ts\n// Read PDF text; for scans, use OCR to turn the image into text\nconst text = readInvoiceText(invoice)\nconst prompt = "Return invoice JSON. Missing values are null: " + text\nlet response = askCheapLLM(prompt)\n// Parse JSON and validate field names and types; invalid data returns null\nlet fields = parseInvoiceJson(response)\n\nif (!fields || !matchesSource(fields, invoice)) {\n  // Keep the original source in the stronger-model prompt\n  response = askSmartLLM(prompt)\n  fields = parseInvoiceJson(response)\n}\n\n// A person checks the source before approval\nqueueForReview(invoice, fields)\n```\n\n**Trade-off:** extra calls on failures. Measure escalation rate and field accuracy; unreadable sources need a better scan, not more speculation.' },
    ],
  },
  {
    slug: 'detect-duplicate-records', title: 'Find duplicate records', question: 'How would you find near-duplicate customer records?',
    description: 'Find exact and near duplicates despite inconsistent names and missing metadata. Similar is not identical, and merging records is a separate, reviewed action.', category: 'Data Systems', difficulty: 'Simple',
    think: ['Which verified identifiers make an exact duplicate?', 'How do you avoid grouping records with missing IDs together?', 'What evidence would justify a merge?'],
    approaches: [
      { title: 'Normalize and compare identifiers', summary: 'Known identifiers before fuzzy matching.', primitives: [], body: 'Do not treat two missing identifiers as an identity match.\n\n```ts\nfor (const record of records) {\n  if (hasVerifiedIdentifier(record)) {\n    const identifier = normalizeIdentifier(record.legalId)\n    const matches = findByIdentifier(identifier, record.tenantId)\n    proposeDuplicateGroup(record, matches)\n  } else {\n    queueForReview(record)\n  }\n}\n```\n\n**Trade-off:** precise, but incomplete records stay unresolved.' },
      { title: 'Find neighbors by meaning', summary: 'Semantic candidates plus deterministic identity checks.', primitives: ['embed', 'similaritySearch'], body: 'Assume records are already indexed using the same embedding model.\n\n```ts\n// Combine the relevant name and address fields into text\nconst description = describeRecord(record)\nconst vector = embed(description)\n// Read saved records and vectors only from this customer account\nconst records = loadRecords(record.tenantId)\n// Compare vectors to find records with similar names and addresses\nconst neighbors = similaritySearch(vector, records)\n\nfor (const other of neighbors) {\n  if (other.id !== record.id && compatibleIdentifiers(record, other)) {\n    showCandidateForReview(record, other)\n  }\n}\n```\n\n**Trade-off:** finds inconsistent spellings, but common names can be misleadingly similar. Measure candidate recall, not automatic merge volume.' },
      { title: 'Prioritize ambiguous pairs', summary: 'An explicit rating helps a reviewer focus.', primitives: ['askDecisionModel'], body: 'A score is a review aid, not an identity proof.\n\n```ts\nfor (const pair of candidatePairs) {\n  const score = askDecisionModel(\n    pair,\n    "Rate identity evidence 1–5. Conflicting legal IDs mean 1."\n  )\n  saveReviewPriority(pair, score)\n}\n\n// Approval and reversible merging stay in your application\nshowDuplicateReviewQueue()\n```\n\n**Trade-off:** adds subjective judgment. Validate on human-labeled pairs, keep evidence visible, and audit false merges.' },
    ],
  },
]

export const problemSummaries: ProblemSummary[] = problems.map(({slug,title,category,difficulty}) => ({slug,title,category,difficulty}))

export const primitiveAliases: Record<string, PrimitiveId> = {
  askCheap: 'askCheapLLM', askSmart: 'askSmartLLM', llm: 'askSmartLLM',
  classify: 'askDecisionModel', classifier: 'askDecisionModel', score: 'askDecisionModel',
  extract: 'askCheapLLM', extraction: 'askCheapLLM', inspect: 'askSmartLLM', multimodal: 'askSmartLLM',
  embeddings: 'embed', search: 'similaritySearch', retrieval: 'similaritySearch', rag: 'similaritySearch',
  rerank: 'askDecisionModel', reranking: 'askDecisionModel', call: 'askSmartLLM', tools: 'askSmartLLM',
  evaluate: 'askDecisionModel', evaluation: 'askDecisionModel',
}
export const problemAliases: Record<string, string> = {
  'route-support-tickets': 'classify-support-tickets',
  'reconcile-bank-transactions': 'reconcile-transactions',
  'natural-language-code-search': 'understand-codebase',
  'investigate-production-logs': 'investigate-production-incidents',
}
export const primitiveById = (id: string) => primitives.find(primitive => primitive.id === id)
export const problemBySlug = (slug: string) => problems.find(problem => problem.slug === slug)
